-- Phase 3 post-build validation for the Patient Experience Command Center accelerator.
-- STRUCTURAL PASS/FAIL/WARN over EVERY deployed derived object the app + agent depend on.
-- FAIL-if-empty = required spine / app-critical serving objects. WARN-if-empty = optional-source-backed
-- objects (provider may lack that source; template present()-gates it off). ACTION_EVENT_LOG is
-- append-only and legitimately empty at go-live (PASS when empty). Non-tabular objects (semantic view,
-- agent, model, search service, stream, task) are checked separately by checks_objects.sql (SHOW-based).
-- Parameterized: replace {{TARGET_DATABASE}}.{{TARGET_SCHEMA}} at run time.
WITH d AS (SELECT '{{TARGET_DATABASE}}.{{TARGET_SCHEMA}}' AS s)
-- ---- Required data spine + models (FAIL if empty) ----
SELECT 'DENORM_SURVEY_RESPONSE_DETAIL' AS CHECK_NAME, IFF(COUNT(*)>0,'PASS','FAIL') AS STATUS, 'rows='||COUNT(*) AS DETAIL FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.DENORM_SURVEY_RESPONSE_DETAIL
UNION ALL SELECT 'DENORM_ENCOUNTER_JOURNEY_DETAIL', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.DENORM_ENCOUNTER_JOURNEY_DETAIL
UNION ALL SELECT 'MDL_STAR_RATING', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_STAR_RATING
UNION ALL SELECT 'MDL_JOURNEY_STAGE_SCORE', IFF(COUNT(*)=5,'PASS','FAIL'),'rows='||COUNT(*)||' (expect 5)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_JOURNEY_STAGE_SCORE
UNION ALL SELECT 'MDL_POINTS_LOST', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_POINTS_LOST
UNION ALL SELECT 'FS_PX_RISK_FEATURES', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.FS_PX_RISK_FEATURES
UNION ALL SELECT 'MDL_DRIVER_IMPORTANCE', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_DRIVER_IMPORTANCE
UNION ALL SELECT 'MDL_DISSAT_RISK', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_DISSAT_RISK
UNION ALL SELECT 'DT_ACTION_WORKQUEUE', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.DT_ACTION_WORKQUEUE
UNION ALL SELECT 'MDL_TAB_INSIGHTS', IFF(COUNT(*)=5,'PASS','FAIL'),'rows='||COUNT(*)||' (expect 5)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_TAB_INSIGHTS
-- ---- Voice / transcription layer ----
UNION ALL SELECT 'CALL_RECORDING_FILE_LOG', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*)||' (optional: recordings stage)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.CALL_RECORDING_FILE_LOG
UNION ALL SELECT 'CALL_TRANSCRIPT', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*)||' (optional: recordings)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.CALL_TRANSCRIPT
UNION ALL SELECT 'COMMENT_ENRICHED', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.COMMENT_ENRICHED
UNION ALL SELECT 'MDL_VOICE_SENTIMENT', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_VOICE_SENTIMENT
-- ---- Optional-source-backed (WARN if empty) ----
UNION ALL SELECT 'DENORM_GRIEVANCE_DETAIL', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*)||' (optional: GRIEVANCE_CASE)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.DENORM_GRIEVANCE_DETAIL
UNION ALL SELECT 'DENORM_CALLBACK_DETAIL', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*)||' (optional: POST_DISCHARGE_CALLBACK)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.DENORM_CALLBACK_DETAIL
UNION ALL SELECT 'MDL_EQUITY_GAP', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*)||' (optional: PATIENT_DEMOGRAPHICS)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_EQUITY_GAP
UNION ALL SELECT 'ACTION_EVENT_LOG', 'PASS','rows='||COUNT(*)||' (append-only; empty at go-live is expected)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.ACTION_EVENT_LOG
-- ---- App serving views (FAIL if empty; app reads these) ----
UNION ALL SELECT 'VW_HOUSE_KPIS', IFF(COUNT(*)=1,'PASS','FAIL'),'rows='||COUNT(*)||' (expect 1)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_HOUSE_KPIS
UNION ALL SELECT 'VW_UNIT_SCORECARD', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_UNIT_SCORECARD
UNION ALL SELECT 'VW_JOURNEY_RIBBON', IFF(COUNT(*)=5,'PASS','FAIL'),'rows='||COUNT(*)||' (expect 5)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_JOURNEY_RIBBON
UNION ALL SELECT 'VW_POINTS_LOST', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_POINTS_LOST
UNION ALL SELECT 'VW_EQUITY_GAP', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_EQUITY_GAP
UNION ALL SELECT 'VW_VOICE_THEMES', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_VOICE_THEMES
UNION ALL SELECT 'VW_DRIVER_IMPORTANCE', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_DRIVER_IMPORTANCE
UNION ALL SELECT 'VW_ACTION_QUEUE', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_ACTION_QUEUE
UNION ALL SELECT 'VW_TAB_INSIGHTS', IFF(COUNT(*)=5,'PASS','FAIL'),'rows='||COUNT(*)||' (expect 5)' FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_TAB_INSIGHTS
UNION ALL SELECT 'VW_WAIT_BY_AREA', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_WAIT_BY_AREA
UNION ALL SELECT 'VW_ACCESS_MOMENTUM', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_ACCESS_MOMENTUM
UNION ALL SELECT 'VW_MEASURE_BENCHMARK', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_MEASURE_BENCHMARK
UNION ALL SELECT 'VW_MEASURE_TREND', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_MEASURE_TREND
UNION ALL SELECT 'VW_DISCHARGE_READINESS', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_DISCHARGE_READINESS
UNION ALL SELECT 'VW_GRIEVANCE_AGING', IFF(COUNT(*)>0,'PASS','WARN'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_GRIEVANCE_AGING
UNION ALL SELECT 'VW_RECOVERY_SLA', IFF(COUNT(*)>0,'PASS','FAIL'),'rows='||COUNT(*) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.VW_RECOVERY_SLA
-- ---- Range / integrity checks ----
UNION ALL SELECT 'HOUSE_COMPOSITE_IN_RANGE', IFF(MAX(IFF(ENTITY_LEVEL='HOUSE',COMPOSITE_TOPBOX,NULL)) BETWEEN 0 AND 100,'PASS','FAIL'),'composite='||MAX(IFF(ENTITY_LEVEL='HOUSE',TO_VARCHAR(COMPOSITE_TOPBOX),NULL)) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_STAR_RATING
UNION ALL SELECT 'HOUSE_STAR_IN_RANGE', IFF(MAX(IFF(ENTITY_LEVEL='HOUSE',STAR_LEVEL,NULL)) BETWEEN 1 AND 5,'PASS','FAIL'),'star='||MAX(IFF(ENTITY_LEVEL='HOUSE',TO_VARCHAR(STAR_LEVEL),NULL)) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_STAR_RATING
UNION ALL SELECT 'RISK_SCORE_IN_RANGE', IFF(MIN(RISK_SCORE)>=0 AND MAX(RISK_SCORE)<=1,'PASS','FAIL'),'min/max='||TO_VARCHAR(ROUND(MIN(RISK_SCORE),3))||'/'||TO_VARCHAR(ROUND(MAX(RISK_SCORE),3)) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_DISSAT_RISK
UNION ALL SELECT 'RISK_TIERS_PRESENT', IFF(COUNT(DISTINCT RISK_TIER)>=2,'PASS','WARN'),'tiers='||TO_VARCHAR(COUNT(DISTINCT RISK_TIER)) FROM {{TARGET_DATABASE}}.{{TARGET_SCHEMA}}.MDL_DISSAT_RISK
ORDER BY DECODE(STATUS,'FAIL',0,'WARN',1,'PASS',2), CHECK_NAME;
