-- ============================================================
-- Teardown: remove everything the PhysicianAssist / MedGemma demo creates.
--
-- Every statement uses IF EXISTS, so this is idempotent and safe to re-run.
-- Identifiers are rewritten for your environment by: python3 configure.py
--
-- READ THE "DO NOT DROP" SECTION AT THE BOTTOM BEFORE EDITING THIS FILE.
--
-- Run order matters: the agent references the procedure and semantic view, the
-- EAI wraps the network rule, and a compute pool cannot be dropped while it
-- still hosts a service.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------
-- 1. Agent
--
-- Drops ONLY the agent. The agent database/schema (default
-- SNOWFLAKE_INTELLIGENCE.AGENTS) is deliberately left alone -- it is a shared
-- account-wide location that almost certainly holds unrelated agents. Do NOT
-- turn create_agent.sql's `CREATE DATABASE IF NOT EXISTS` into a DROP DATABASE.
-- ------------------------------------------------------------

DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.HIMSS_PHYSICIAN_AGENT;

-- ------------------------------------------------------------
-- 2. MedGemma SPCS service
--
-- The service name is generated by the Snowsight model-deployment wizard and
-- includes a timestamp, e.g.
--   MEDGEMMA_4B_IT_V_2026_02_24__17_20_05_SERVICE
-- so it cannot be hardcoded. Find yours first:
--
--   SHOW SERVICES IN COMPUTE POOL MEDGEMMA_COMPUTE_POOL;
--
-- then substitute it below. A compute pool will refuse to drop while a service
-- is still attached.
-- ------------------------------------------------------------

DROP SERVICE IF EXISTS MEDGEMMA_DEMO.PUBLIC.<YOUR_MEDGEMMA_SERVICE_NAME>;

-- ------------------------------------------------------------
-- 3. Compute pool
--
-- Check nothing else is attached before dropping (num_services should be 0
-- after step 2):
--   SHOW COMPUTE POOLS LIKE 'MEDGEMMA_COMPUTE_POOL';
-- ------------------------------------------------------------

DROP COMPUTE POOL IF EXISTS MEDGEMMA_COMPUTE_POOL;

-- ------------------------------------------------------------
-- 4. External access integrations
--
-- MEDGEMMA_SPCS_EAI  - created by deploy_medgemma.sql, lets the stored
--                      procedure reach the SPCS REST endpoint. Wraps the
--                      network rule dropped with the schema in step 5, so it
--                      must go first.
-- MEDGEMMA_EAI       - created by the Snowsight model-deployment wizard for the
--                      HuggingFace model download.
--
-- Both are MedGemma-specific. Other HuggingFace access paths in a typical
-- account (HF_INTEGRATION, ALLOW_ALL_EAI) are unaffected.
-- ------------------------------------------------------------

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS MEDGEMMA_SPCS_EAI;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS MEDGEMMA_EAI;

-- ------------------------------------------------------------
-- 5. Demo schema (CASCADE)
--
-- Removes, in one statement:
--   - 6 base tables: PATIENTS, CONDITIONS, MEDICATIONS, VITALS, ENCOUNTERS,
--     MEDICAL_IMAGES
--   - any *_IT interactive tables built from them
--   - MEDGEMMA_MEDICAL_INTERPRETER, plus any earlier INTERPRET_* iterations
--   - HIMSS_PATIENT_SEMANTIC_VIEW
--   - SEMANTIC_STAGE
--   - MEDGEMMA_PAT_SECRET
--   - the MedGemma egress network rule
--
-- CASCADE is intentional: it catches objects added by hand during a demo build
-- that the setup scripts never created. If you have put anything unrelated in
-- this schema, drop objects individually instead.
-- ------------------------------------------------------------

DROP SCHEMA IF EXISTS DEMO_DB.HIMSS_DEMO CASCADE;

-- ------------------------------------------------------------
-- 6. MedGemma database
--
-- Removes ECG_STAGE and any batch output stage, IMAGE_REPO (the container image
-- repository), and the HuggingFace token secret.
--
-- Note this drops the pushed MedGemma container image. Re-running
-- deploy_medgemma.sql means re-deploying the model, which is slow.
-- ------------------------------------------------------------

DROP DATABASE IF EXISTS MEDGEMMA_DEMO;

-- ============================================================
-- Verify (all should return no rows)
-- ============================================================

SHOW AGENTS LIKE 'HIMSS_PHYSICIAN_AGENT' IN ACCOUNT;
SHOW COMPUTE POOLS LIKE 'MEDGEMMA_COMPUTE_POOL';
SHOW EXTERNAL ACCESS INTEGRATIONS LIKE 'MEDGEMMA%';
SHOW SCHEMAS LIKE 'HIMSS_DEMO' IN DATABASE DEMO_DB;
SHOW DATABASES LIKE 'MEDGEMMA_DEMO';

-- ============================================================
-- DO NOT DROP -- the demo does not create these
--
-- Dropping any of the following will damage unrelated work:
--
--   SNOWFLAKE_INTELLIGENCE (database/schema)
--       Shared location for every agent in the account. create_agent.sql only
--       creates it IF NOT EXISTS; teardown must remove the agent, not the
--       container.
--
--   DEMO_DB (database)
--       Typically the account's general-purpose demo database with many
--       unrelated schemas and semantic views. Only the HIMSS_DEMO schema
--       belongs to this demo.
--
--   Warehouses (e.g. DEMO_BUILD_WH, HIMSS_INTERACTIVE_WH)
--       Referenced by the demo, never created by it.
--
--   GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN
--       deploy_medgemma.sql issues this grant, but it is account-wide and
--       shared by every service with public ingress. Revoking it can break
--       unrelated running services. Leave it in place.
--
--   GRANT USAGE ON COMPUTE POOL ... TO ROLE SYSADMIN
--       Disappears with the compute pool in step 3; no separate revoke needed.
-- ============================================================
