-- ============================================================
-- Teardown: remove everything the PhysicianAssist / MedGemma demo creates.
--
-- Safe to re-run: every statement is guarded with IF EXISTS, and the ordering
-- avoids referencing an object inside a database that may already be gone.
-- Identifiers are rewritten for your environment by: python3 configure.py
--
-- READ THE "DO NOT DROP" SECTION AT THE BOTTOM BEFORE EDITING THIS FILE.
--
-- Ordering rationale:
--   * The agent goes first -- it references the procedure and semantic view.
--   * The EAI is dropped before the network rule it wraps (the rule lives in the
--     demo schema, removed in step 3).
--   * The MedGemma database is dropped BEFORE the compute pool. Dropping the
--     database removes the SPCS service it contains, which in turn frees the
--     pool -- a compute pool will not drop while a service is still attached.
--     This also avoids having to name the service, whose name is generated by
--     the Snowsight model-deployment wizard and carries a timestamp.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------
-- 1. Agent
--
-- Drops ONLY the agent. The agent database/schema (default
-- SNOWFLAKE_INTELLIGENCE.AGENTS) is deliberately left alone -- it is a shared
-- account-wide location that almost certainly holds unrelated agents. Do NOT
-- turn create_agent.sql's `CREATE DATABASE IF NOT EXISTS` into a DROP DATABASE.
-- ------------------------------------------------------------

DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.HIMSS_PHYSICIAN_AGENT;

-- ------------------------------------------------------------
-- 2. External access integrations
--
-- MEDGEMMA_SPCS_EAI  - created by deploy_medgemma.sql, lets the stored
--                      procedure reach the SPCS REST endpoint. Wraps the
--                      network rule removed with the schema in step 3, so it
--                      must go first.
-- MEDGEMMA_EAI       - created by the Snowsight model-deployment wizard for the
--                      HuggingFace model download.
--
-- Both are MedGemma-specific. Other HuggingFace access paths in a typical
-- account (HF_INTEGRATION, ALLOW_ALL_EAI) are unaffected.
-- ------------------------------------------------------------

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS MEDGEMMA_SPCS_EAI;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS MEDGEMMA_EAI;

-- ------------------------------------------------------------
-- 3. Demo schema (CASCADE)
--
-- Removes, in one statement:
--   - 6 base tables: PATIENTS, CONDITIONS, MEDICATIONS, VITALS, ENCOUNTERS,
--     MEDICAL_IMAGES
--   - any *_IT interactive tables built from them
--   - MEDGEMMA_MEDICAL_INTERPRETER, plus any earlier INTERPRET_* iterations
--   - HIMSS_PATIENT_SEMANTIC_VIEW
--   - SEMANTIC_STAGE
--   - MEDGEMMA_PAT_SECRET
--   - the MedGemma egress network rule
--
-- CASCADE is intentional: it catches objects added by hand during a demo build
-- that the setup scripts never created. If you have put anything unrelated in
-- this schema, drop objects individually instead.
-- ------------------------------------------------------------

DROP SCHEMA IF EXISTS DEMO_DB.HIMSS_DEMO CASCADE;

-- ------------------------------------------------------------
-- 4. MedGemma database
--
-- Removes the SPCS service, ECG_STAGE and any batch output stage, IMAGE_REPO
-- (the container image repository), and the HuggingFace token secret.
--
-- This drops the pushed MedGemma container image. Re-running
-- deploy_medgemma.sql means re-deploying the model, which is slow.
--
-- If this is blocked because the service is still running, suspend and drop the
-- service explicitly first, then re-run. The service name is wizard-generated
-- with a timestamp, so look it up:
--
--   SHOW SERVICES IN COMPUTE POOL MEDGEMMA_COMPUTE_POOL;
--   ALTER SERVICE MEDGEMMA_DEMO.PUBLIC.<YOUR_MEDGEMMA_SERVICE_NAME> SUSPEND;
--   DROP SERVICE IF EXISTS MEDGEMMA_DEMO.PUBLIC.<YOUR_MEDGEMMA_SERVICE_NAME>;
-- ------------------------------------------------------------

DROP DATABASE IF EXISTS MEDGEMMA_DEMO;

-- ------------------------------------------------------------
-- 5. Compute pool
--
-- Step 4 removed the only service on this pool. Confirm nothing else attached
-- before dropping (num_services should be 0):
--   SHOW COMPUTE POOLS LIKE 'MEDGEMMA_COMPUTE_POOL';
-- ------------------------------------------------------------

DROP COMPUTE POOL IF EXISTS MEDGEMMA_COMPUTE_POOL;

-- ============================================================
-- Verify (all should return no rows)
-- ============================================================

SHOW AGENTS LIKE 'HIMSS_PHYSICIAN_AGENT' IN ACCOUNT;
SHOW EXTERNAL ACCESS INTEGRATIONS LIKE 'MEDGEMMA%';
SHOW SCHEMAS LIKE 'HIMSS_DEMO' IN DATABASE DEMO_DB;
SHOW DATABASES LIKE 'MEDGEMMA_DEMO';
SHOW COMPUTE POOLS LIKE 'MEDGEMMA_COMPUTE_POOL';

-- ============================================================
-- DO NOT DROP -- the demo does not create these
--
-- Dropping any of the following will damage unrelated work:
--
--   SNOWFLAKE_INTELLIGENCE (database/schema)
--       Shared location for every agent in the account. create_agent.sql only
--       creates it IF NOT EXISTS; teardown must remove the agent, not the
--       container.
--
--   DEMO_DB (database)
--       Typically the account's general-purpose demo database with many
--       unrelated schemas and semantic views. Only the HIMSS_DEMO schema
--       belongs to this demo.
--
--   Warehouses (e.g. DEMO_BUILD_WH, HIMSS_INTERACTIVE_WH)
--       Referenced by the demo, never created by it.
--
--   GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN
--       deploy_medgemma.sql issues this grant, but it is account-wide and
--       shared by every service with public ingress. Revoking it can break
--       unrelated running services. Leave it in place.
--
--   GRANT USAGE ON COMPUTE POOL ... TO ROLE SYSADMIN
--       Disappears with the compute pool in step 5; no separate revoke needed.
--
-- A note on names: the objects actually deployed may not match the names in
-- these scripts, because the SPCS pieces are created through the Snowsight
-- wizard rather than by SQL. On the reference deployment the pool was
-- MEDGEMMA_COMPUTE_POOL (not MEDGEMMA_GPU_POOL), the network rule
-- MEDGEMMA_SPCS_NR, and the HuggingFace secret MEDGEMMA_HUGGING_FACE_TOKEN.
-- Because every statement uses IF EXISTS, a name mismatch fails silently and
-- leaves objects behind -- run the verification queries above and confirm they
-- return no rows.
-- ============================================================
