import json
import logging
import os
import tempfile
from io import BytesIO
from pathlib import Path
from typing import Any

import httpx
import snowflake.connector
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Denied Claims Data API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DB = os.environ.get("SNOWFLAKE_DATABASE", "AGENTIC_DENIED_CLAIMS_HANDLING")
SCHEMA = os.environ.get("SNOWFLAKE_SCHEMA", "DENIED_CLAIMS")
WH = os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH")


def _get_connection():
    token_path = Path("/snowflake/session/token")
    if token_path.exists():
        creds: dict[str, Any] = {
            "host": os.environ.get("SNOWFLAKE_HOST"),
            "account": os.environ.get("SNOWFLAKE_ACCOUNT"),
            "authenticator": "oauth",
            "token": token_path.read_text().strip(),
            "warehouse": WH,
            "database": DB,
            "schema": SCHEMA,
            "client_session_keep_alive": True,
        }
        spcs_port = os.environ.get("SNOWFLAKE_PORT")
        if spcs_port:
            creds["port"] = int(spcs_port)
            creds["protocol"] = "https"
        logger.info(f"SPCS connect: host={creds['host']}, account={creds['account']}")
        return snowflake.connector.connect(**creds)
    return snowflake.connector.connect(
        connection_name=os.getenv("SNOWFLAKE_CONNECTION_NAME", "default")
    )


def _query(sql: str, params: tuple = ()) -> list[dict]:
    conn = _get_connection()
    try:
        cur = conn.cursor(snowflake.connector.DictCursor)
        cur.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]
    finally:
        conn.close()


def _serialize(rows: list[dict]) -> list[dict]:
    out = []
    for r in rows:
        row = {}
        for k, v in r.items():
            if hasattr(v, "isoformat"):
                row[k] = v.isoformat()
            elif isinstance(v, (int, float, str, bool, type(None))):
                row[k] = v
            else:
                row[k] = str(v)
        out.append(row)
    return out


def _execute(sql: str, params: tuple = ()):
    conn = _get_connection()
    try:
        cur = conn.cursor()
        cur.execute(sql, params)
    finally:
        conn.close()


def _execute_put(local_path: str, stage_path: str):
    conn = _get_connection()
    try:
        cur = conn.cursor()
        cur.execute(f"PUT 'file://{local_path}' '{stage_path}' AUTO_COMPRESS=FALSE OVERWRITE=TRUE")
    finally:
        conn.close()


def _build_docx(
    provider_name: str, provider_npi: str, member_name: str, member_id: str,
    plan_id: str, dos: str, claim_id: str, denial_id: str,
    denial_code: str, denial_reason: str, appeal_body: str, policy_citations: str,
) -> BytesIO:
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)
    style.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    draft = doc.add_paragraph()
    draft.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = draft.add_run("DRAFT — GENERATED BY AI AGENT")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    run.bold = True

    header_para = doc.add_paragraph()
    header_para.space_after = Pt(4)
    run = header_para.add_run(provider_name or "Provider")
    run.bold = True
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x11, 0x56, 0x7F)

    sub = doc.add_paragraph()
    sub.space_after = Pt(2)
    sub.add_run(f"NPI: {provider_npi or 'N/A'}").font.size = Pt(9)

    from datetime import datetime
    date_para = doc.add_paragraph()
    date_para.space_after = Pt(16)
    date_para.add_run(datetime.now().strftime("%B %d, %Y")).font.size = Pt(10)

    doc.add_paragraph("")

    re_block = doc.add_paragraph()
    re_block.space_after = Pt(12)
    run = re_block.add_run("RE: Appeal of Claim Denial\n")
    run.bold = True
    run.font.size = Pt(11)
    for line in [
        f"Claim Number: {claim_id}",
        f"Member: {member_name}, ID: {member_id}",
        f"Plan: {plan_id}",
        f"Date of Service: {dos}",
        f"Denial Code: {denial_code} — {denial_reason}",
    ]:
        re_block.add_run(f"{line}\n").font.size = Pt(10)

    doc.add_paragraph("")

    for para_text in (appeal_body or "").split("\n\n"):
        para_text = para_text.strip()
        if not para_text:
            continue
        p = doc.add_paragraph()
        p.space_after = Pt(8)
        p.add_run(para_text).font.size = Pt(11)

    if policy_citations and policy_citations.strip():
        doc.add_paragraph("")
        ch = doc.add_paragraph()
        ch.space_after = Pt(4)
        run = ch.add_run("Policy Citations Referenced")
        run.bold = True
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x11, 0x56, 0x7F)
        for c in policy_citations.split(","):
            c = c.strip()
            if c:
                cp = doc.add_paragraph(style="List Bullet")
                cp.add_run(c).font.size = Pt(10)

    doc.add_paragraph("")
    sig = doc.add_paragraph()
    sig.add_run("Sincerely,\n").font.size = Pt(11)
    sig.add_run("\n")
    run = sig.add_run(provider_name or "Provider")
    run.bold = True
    run.font.size = Pt(11)
    sig.add_run(f"\nNPI: {provider_npi or 'N/A'}").font.size = Pt(10)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


@app.get("/data/queue")
async def get_queue(unprocessed: bool = False):
    filter_clause = "WHERE d.PROCESSED_BY_AGENT = false" if unprocessed else ""
    sql = f"""
    SELECT d.DENIAL_ID, d.CLAIM_ID, d.DENIAL_CODE, d.DENIAL_REASON, d.DENIAL_AMOUNT,
           d.DENIAL_DATE, d.PAYER_REMARK,
           d.PROCESSED_BY_AGENT, d.AGENT_PROCESSED_AT,
           c.PROVIDER_NAME, c.DATE_OF_SERVICE, c.TOTAL_BILLED,
           c.PRIMARY_DIAGNOSIS, c.DIAGNOSIS_DESCRIPTION, c.PROVIDER_NPI, c.GROUP_NPI,
           c.FACILITY_NAME, c.PAYER_ID,
           m.FIRST_NAME || ' ' || m.LAST_NAME AS PATIENT_NAME,
           m.MEMBER_ID, m.PLAN_ID
    FROM {DB}.{SCHEMA}.DENIALS d
    JOIN {DB}.{SCHEMA}.CLAIMS c ON d.CLAIM_ID = c.CLAIM_ID
    JOIN {DB}.{SCHEMA}.MEMBERS m ON c.MEMBER_ID = m.MEMBER_ID
    {filter_clause}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY d.CLAIM_ID ORDER BY d.PROCESSED_BY_AGENT DESC, d.DENIAL_ID) = 1
    ORDER BY d.DENIAL_AMOUNT DESC
    """
    rows = _serialize(_query(sql))
    return {"denials": rows, "count": len(rows)}


@app.get("/data/results/{claim_id}")
async def get_results(claim_id: str):
    denial_sql = f"""
    SELECT d.DENIAL_ID, d.CLAIM_ID, d.DENIAL_CODE, d.DENIAL_REASON, d.DENIAL_AMOUNT,
           d.PROCESSED_BY_AGENT, d.AGENT_RESULT,
           c.PROVIDER_NAME, c.DATE_OF_SERVICE, c.TOTAL_BILLED,
           c.PRIMARY_DIAGNOSIS, c.DIAGNOSIS_DESCRIPTION, c.PROVIDER_NPI,
           m.FIRST_NAME || ' ' || m.LAST_NAME AS PATIENT_NAME, m.MEMBER_ID, m.PLAN_ID
    FROM {DB}.{SCHEMA}.DENIALS d
    JOIN {DB}.{SCHEMA}.CLAIMS c ON d.CLAIM_ID = c.CLAIM_ID
    JOIN {DB}.{SCHEMA}.MEMBERS m ON c.MEMBER_ID = m.MEMBER_ID
    WHERE d.CLAIM_ID = %s
    ORDER BY d.PROCESSED_BY_AGENT DESC
    LIMIT 1
    """
    denials = _query(denial_sql, (claim_id,))
    if not denials:
        raise HTTPException(status_code=404, detail=f"Claim {claim_id} not found")
    denial = denials[0]

    agent_result_raw = denial.pop("AGENT_RESULT", None)
    agent_result = None
    if agent_result_raw:
        if isinstance(agent_result_raw, str):
            try:
                agent_result = json.loads(agent_result_raw)
            except Exception:
                agent_result = None
        elif isinstance(agent_result_raw, dict):
            agent_result = agent_result_raw

    work_items = _query(
        f"SELECT * FROM {DB}.{SCHEMA}.DENIAL_WORK_ITEMS WHERE CLAIM_ID = %s ORDER BY CREATED_AT DESC",
        (claim_id,),
    )
    notes = _query(
        f"SELECT * FROM {DB}.{SCHEMA}.DENIAL_NOTES WHERE CLAIM_ID = %s ORDER BY CREATED_AT DESC",
        (claim_id,),
    )
    drafts = _query(
        f"SELECT * FROM {DB}.{SCHEMA}.APPEAL_DRAFTS WHERE CLAIM_ID = %s ORDER BY CREATED_AT DESC",
        (claim_id,),
    )

    return {
        "denial": _serialize([denial])[0],
        "agent_result": agent_result,
        "work_items": _serialize(work_items),
        "notes": _serialize(notes),
        "appeal_drafts": _serialize(drafts),
    }


@app.get("/data/appeal-doc/{claim_id}")
async def get_appeal_doc(claim_id: str):
    drafts = _query(
        f"SELECT DOCX_STAGE_PATH, APPEAL_BODY, POLICY_CITATIONS FROM {DB}.{SCHEMA}.APPEAL_DRAFTS WHERE CLAIM_ID = %s ORDER BY CREATED_AT DESC LIMIT 1",
        (claim_id,),
    )
    if not drafts:
        raise HTTPException(status_code=404, detail="No appeal draft found")

    stage_path = drafts[0].get("DOCX_STAGE_PATH")
    if stage_path:
        try:
            url_rows = _query(
                f"SELECT GET_PRESIGNED_URL('@{DB}.{SCHEMA}.APPEAL_DOCUMENTS', %s, 3600) AS URL",
                (stage_path,),
            )
            if url_rows and url_rows[0].get("URL"):
                return {"type": "presigned_url", "url": url_rows[0]["URL"], "filename": f"Appeal_{claim_id}.docx"}
        except Exception as e:
            logger.warning(f"Failed to get presigned URL for {stage_path}: {e}")

    denial = _query(
        f"""SELECT c.PROVIDER_NAME, c.PROVIDER_NPI, c.DATE_OF_SERVICE,
                   d.DENIAL_CODE, d.DENIAL_REASON, d.DENIAL_ID,
                   m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME, m.MEMBER_ID, m.PLAN_ID
            FROM {DB}.{SCHEMA}.DENIALS d
            JOIN {DB}.{SCHEMA}.CLAIMS c ON d.CLAIM_ID = c.CLAIM_ID
            JOIN {DB}.{SCHEMA}.MEMBERS m ON c.MEMBER_ID = m.MEMBER_ID
            WHERE d.CLAIM_ID = %s LIMIT 1""",
        (claim_id,),
    )
    ctx = denial[0] if denial else {}
    buf = _build_docx(
        provider_name=ctx.get("PROVIDER_NAME", ""),
        provider_npi=ctx.get("PROVIDER_NPI", ""),
        member_name=ctx.get("MEMBER_NAME", ""),
        member_id=ctx.get("MEMBER_ID", ""),
        plan_id=ctx.get("PLAN_ID", ""),
        dos=str(ctx.get("DATE_OF_SERVICE", "")),
        claim_id=claim_id,
        denial_id=ctx.get("DENIAL_ID", ""),
        denial_code=ctx.get("DENIAL_CODE", ""),
        denial_reason=ctx.get("DENIAL_REASON", ""),
        appeal_body=drafts[0].get("APPEAL_BODY", ""),
        policy_citations=drafts[0].get("POLICY_CITATIONS", ""),
    )
    return StreamingResponse(
        buf,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="Appeal_{claim_id}.docx"'},
    )


class ReviewRequest(BaseModel):
    action: str
    notes: str = ""


@app.post("/data/appeal-review/{claim_id}")
async def review_appeal(claim_id: str, body: ReviewRequest):
    status_map = {"approve": "APPROVED", "request_changes": "CHANGES_REQUESTED", "reject": "REJECTED"}
    status = status_map.get(body.action, "DRAFT")
    _execute(
        f"UPDATE {DB}.{SCHEMA}.APPEAL_DRAFTS SET REVIEW_STATUS = %s, REVIEWER_NOTES = %s, REVIEWED_AT = CURRENT_TIMESTAMP() WHERE CLAIM_ID = %s",
        (status, body.notes, claim_id),
    )
    return {"status": status, "claim_id": claim_id}


class AppealSaveRequest(BaseModel):
    appeal_body: str
    policy_citations: str = ""


@app.post("/data/appeal-save/{claim_id}")
async def save_appeal(claim_id: str, body: AppealSaveRequest):
    _execute(
        f"UPDATE {DB}.{SCHEMA}.APPEAL_DRAFTS SET APPEAL_BODY = %s, POLICY_CITATIONS = %s, REVIEW_STATUS = 'REVISED' WHERE CLAIM_ID = %s",
        (body.appeal_body, body.policy_citations, claim_id),
    )

    denial = _query(
        f"""SELECT c.PROVIDER_NAME, c.PROVIDER_NPI, c.DATE_OF_SERVICE,
                   d.DENIAL_CODE, d.DENIAL_REASON, d.DENIAL_ID,
                   m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME, m.MEMBER_ID, m.PLAN_ID
            FROM {DB}.{SCHEMA}.DENIALS d
            JOIN {DB}.{SCHEMA}.CLAIMS c ON d.CLAIM_ID = c.CLAIM_ID
            JOIN {DB}.{SCHEMA}.MEMBERS m ON c.MEMBER_ID = m.MEMBER_ID
            WHERE d.CLAIM_ID = %s LIMIT 1""",
        (claim_id,),
    )
    ctx = denial[0] if denial else {}
    buf = _build_docx(
        provider_name=ctx.get("PROVIDER_NAME", ""),
        provider_npi=ctx.get("PROVIDER_NPI", ""),
        member_name=ctx.get("MEMBER_NAME", ""),
        member_id=ctx.get("MEMBER_ID", ""),
        plan_id=ctx.get("PLAN_ID", ""),
        dos=str(ctx.get("DATE_OF_SERVICE", "")),
        claim_id=claim_id,
        denial_id=ctx.get("DENIAL_ID", ""),
        denial_code=ctx.get("DENIAL_CODE", ""),
        denial_reason=ctx.get("DENIAL_REASON", ""),
        appeal_body=body.appeal_body,
        policy_citations=body.policy_citations,
    )

    with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
        tmp.write(buf.read())
        tmp_path = tmp.name

    try:
        stage_path = f"@{DB}.{SCHEMA}.APPEAL_DOCUMENTS/{claim_id}/"
        _execute_put(tmp_path, stage_path)
        rel_path = f"{claim_id}/Appeal_{claim_id}.docx"
        _execute(
            f"UPDATE {DB}.{SCHEMA}.APPEAL_DRAFTS SET DOCX_STAGE_PATH = %s WHERE CLAIM_ID = %s",
            (rel_path, claim_id),
        )
    except Exception as e:
        logger.warning(f"Failed to upload revised DOCX to stage: {e}")
    finally:
        os.unlink(tmp_path)

    return {"status": "saved", "claim_id": claim_id}


# =============================================================================
# INTERACTIVE AGENT — Cortex Agent REST API proxy
# =============================================================================

SEMANTIC_VIEW_FQN = os.environ.get("CORTEX_SEMANTIC_VIEW", f"{DB}.{SCHEMA}.DENIED_CLAIMS_AGENT_SV")
SEARCH_SERVICE = os.environ.get("CORTEX_SEARCH_SERVICE", f"{DB}.{SCHEMA}.PAYER_DOC_SEARCH")



class ChatMessage(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    claim_context: dict[str, Any] | None = None


class ApproveRequest(BaseModel):
    action: str
    notes: str = ""


def _build_system_prompt(claim_context: dict | None) -> str:
    base = (
        "You are an expert denied claims resolution specialist assistant for a Provider RCM team. "
        "You have two tools available:\n"
        "1. payer_doc_search — search payer policy documents, contract sections, and appeal procedures\n"
        "2. claims_analyst — answer data questions about claims, denials, members, prior authorizations, "
        "contracts, historical overturn rates, investigation notes, and appeal drafts\n\n"
        "Guidelines:\n"
        "- Be concise, specific, and clinically precise\n"
        "- Never fabricate policy citations — only cite what you find via payer_doc_search\n"
        "- When quoting contract text, always include the section number\n"
        "- Proactively flag deadline risks (filing window, appeal window)\n"
        "- Use claims_analyst for any data question (overturn rates, auth lookups, contract terms, etc.)\n"
        "- Use payer_doc_search for specific policy language, coverage criteria, and appeal procedures\n"
    )
    if not claim_context:
        return base
    denial = claim_context.get("denial", {})
    agent_result = claim_context.get("agent_result") or {}
    work_items = claim_context.get("work_items") or []
    notes = claim_context.get("notes") or []
    appeal_drafts = claim_context.get("appeal_drafts") or []
    wi = work_items[0] if work_items else {}
    draft = appeal_drafts[0] if appeal_drafts else {}
    note = notes[0] if notes else {}
    context_block = (
        f"\n\nCURRENT CLAIM CONTEXT (use this as your starting point — do not re-query for these facts):\n"
        f"Claim ID: {denial.get('CLAIM_ID', 'N/A')}\n"
        f"Patient: {denial.get('PATIENT_NAME', 'N/A')}\n"
        f"Denial Code: {denial.get('DENIAL_CODE', 'N/A')} — {denial.get('DENIAL_REASON', 'N/A')}\n"
        f"Denial Amount: ${denial.get('DENIAL_AMOUNT', 'N/A')}\n"
        f"Provider: {denial.get('PROVIDER_NAME', 'N/A')}\n"
        f"Payer ID: {denial.get('PAYER_ID', denial.get('PLAN_ID', 'N/A'))}\n"
        f"Date of Service: {denial.get('DATE_OF_SERVICE', 'N/A')}\n"
        f"Worker Agent Category: {agent_result.get('denial_category', 'N/A')}\n"
        f"Worker Agent Strategy: {agent_result.get('recommended_strategy', 'N/A')} "
        f"(confidence: {round((agent_result.get('confidence') or 0) * 100)}%)\n"
        f"Worker Agent Root Cause: {agent_result.get('root_cause', 'N/A')}\n"
        f"Evidence Summary: {agent_result.get('evidence_summary', 'N/A')}\n"
        f"Priority: {agent_result.get('priority', wi.get('PRIORITY', 'N/A'))}\n"
        f"Queue: {wi.get('QUEUE', 'N/A')} — Work Item: {wi.get('WORK_ITEM_ID', 'N/A')}\n"
        f"Appeal Draft Status: {draft.get('REVIEW_STATUS', 'N/A')}\n"
        f"Policy Citations in Draft: {draft.get('POLICY_CITATIONS', 'N/A')}\n"
        f"Investigation Notes: {(note.get('NOTE_TEXT') or '')[:400]}\n"
    )
    return base + context_block


@app.post("/data/chat")
async def chat(body: ChatRequest):
    cortex_host = os.environ.get("CORTEX_HOST", os.environ.get("SNOWFLAKE_HOST", ""))
    pat = os.environ.get("CORTEX_CODE_PAT", "")
    token_path = Path("/snowflake/session/token")
    if pat:
        token = pat
        host = cortex_host
    elif token_path.exists():
        token = token_path.read_text().strip()
        host = cortex_host
    else:
        token = os.environ.get("SNOWFLAKE_PAT", "")
        host = cortex_host
        if not token or not host:
            raise HTTPException(
                status_code=503,
                detail="Cortex Agent requires CORTEX_HOST + auth token"
            )

    system_prompt = _build_system_prompt(body.claim_context)
    payload = {
        "messages": [
            *[{"role": m.role, "content": [{"type": "text", "text": m.content}]} for m in body.messages if m.content and m.content.strip()],
        ],
        "instructions": {
            "system": system_prompt,
        },
        "tools": [
            {
                "tool_spec": {
                    "type": "cortex_search",
                    "name": "payer_doc_search",
                }
            },
            {
                "tool_spec": {
                    "type": "cortex_analyst_text_to_sql",
                    "name": "claims_analyst",
                }
            },
        ],
        "tool_resources": {
            "payer_doc_search": {
                "search_service": SEARCH_SERVICE,
            },
            "claims_analyst": {
                "semantic_view": SEMANTIC_VIEW_FQN,
                "execution_environment": {
                    "type": "warehouse",
                    "warehouse": WH,
                },
            },
        },
    }

    async def stream_response():
        try:
            async with httpx.AsyncClient(timeout=120.0) as client:
                async with client.stream(
                    "POST",
                    f"https://{host}/api/v2/cortex/agent:run",
                    headers={
                        "Authorization": f"Bearer {token}",
                        "Content-Type": "application/json",
                        "Accept": "text/event-stream",
                    },
                    json=payload,
                ) as resp:
                    if resp.status_code != 200:
                        error_body = await resp.aread()
                        logger.error(f"Cortex Agent API error {resp.status_code}: {error_body.decode()[:500]}")
                        yield f"data: {{\"error\": \"Cortex Agent API returned {resp.status_code}\"}}\n\n"
                        return
                    async for chunk in resp.aiter_text():
                        if chunk:
                            yield chunk
        except Exception as e:
            logger.exception("Error streaming from Cortex Agent API")
            yield f"data: {{\"error\": \"{str(e)[:200]}\"}}\n\n"

    return StreamingResponse(
        stream_response(),
        media_type="text/event-stream",
        headers={
            "X-Accel-Buffering": "no",
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
        },
    )


@app.post("/data/approve/{claim_id}")
async def approve_claim(claim_id: str, body: ApproveRequest):
    status_map = {"approve": "OVERTURNED", "reject": "WRITE_OFF"}
    status = status_map.get(body.action, "OPEN")
    _execute(
        f"UPDATE {DB}.{SCHEMA}.DENIAL_WORK_ITEMS SET STATUS = %s, UPDATED_AT = CURRENT_TIMESTAMP() WHERE CLAIM_ID = %s",
        (status, claim_id),
    )
    if body.notes:
        _execute(
            f"INSERT INTO {DB}.{SCHEMA}.DENIAL_NOTES (NOTE_ID, CLAIM_ID, NOTE_TYPE, NOTE_TEXT, CREATED_BY) "
            f"VALUES (UUID_STRING(), %s, 'HUMAN_REVIEW', %s, 'SPECIALIST')",
            (claim_id, f"Specialist {body.action}: {body.notes}"),
        )
    return {"status": status, "claim_id": claim_id, "action": body.action}


@app.get("/data/health")
async def health():
    return {"status": "ok"}


class ResetRequest(BaseModel):
    claim_ids: list[str] | None = None
    mode: str = "seed"


@app.get("/data/reset-claims")
async def get_reset_claims():
    rows = _query(
        f"""SELECT d.DENIAL_ID, d.CLAIM_ID, d.DENIAL_CODE, d.DENIAL_AMOUNT,
                   d.PROCESSED_BY_AGENT,
                   m.FIRST_NAME || ' ' || m.LAST_NAME AS PATIENT_NAME
            FROM {DB}.{SCHEMA}.DENIALS d
            JOIN {DB}.{SCHEMA}.CLAIMS c ON d.CLAIM_ID = c.CLAIM_ID
            JOIN {DB}.{SCHEMA}.MEMBERS m ON c.MEMBER_ID = m.MEMBER_ID
            ORDER BY d.DENIAL_AMOUNT DESC"""
    )
    return {"claims": _serialize(rows)}


def _reset_claims(claim_ids: list[str]):
    placeholders = ",".join(["%s"] * len(claim_ids))
    params = tuple(claim_ids)
    _execute(
        f"DELETE FROM {DB}.{SCHEMA}.DENIAL_WORK_ITEMS WHERE CREATED_BY = 'DENIAL_AGENT' AND CLAIM_ID IN ({placeholders})",
        params,
    )
    _execute(
        f"DELETE FROM {DB}.{SCHEMA}.DENIAL_NOTES WHERE CREATED_BY = 'DENIAL_AGENT' AND CLAIM_ID IN ({placeholders})",
        params,
    )
    _execute(
        f"DELETE FROM {DB}.{SCHEMA}.APPEAL_DRAFTS WHERE CREATED_BY = 'DENIAL_AGENT' AND CLAIM_ID IN ({placeholders})",
        params,
    )
    _execute(
        f"UPDATE {DB}.{SCHEMA}.DENIALS SET PROCESSED_BY_AGENT = false, AGENT_RESULT = NULL, AGENT_PROCESSED_AT = NULL WHERE CLAIM_ID IN ({placeholders})",
        params,
    )
    for cid in claim_ids:
        try:
            _execute(f"REMOVE @{DB}.{SCHEMA}.APPEAL_DOCUMENTS/{cid}/")
        except Exception:
            pass


def _restore_seed():
    _execute(f"INSERT INTO {DB}.{SCHEMA}.DENIAL_WORK_ITEMS SELECT * FROM {DB}.{SCHEMA}.SEED_DENIAL_WORK_ITEMS")
    _execute(f"INSERT INTO {DB}.{SCHEMA}.DENIAL_NOTES SELECT * FROM {DB}.{SCHEMA}.SEED_DENIAL_NOTES")
    _execute(f"INSERT INTO {DB}.{SCHEMA}.APPEAL_DRAFTS SELECT * FROM {DB}.{SCHEMA}.SEED_APPEAL_DRAFTS")
    _execute(
        f"UPDATE {DB}.{SCHEMA}.DENIALS d SET d.PROCESSED_BY_AGENT = true, "
        f"d.AGENT_RESULT = s.AGENT_RESULT, d.AGENT_PROCESSED_AT = s.AGENT_PROCESSED_AT "
        f"FROM {DB}.{SCHEMA}.SEED_DENIALS_AGENT_STATE s WHERE d.DENIAL_ID = s.DENIAL_ID"
    )
    try:
        _execute(
            f"COPY FILES INTO @{DB}.{SCHEMA}.APPEAL_DOCUMENTS/ "
            f"FROM @{DB}.{SCHEMA}.SEED_APPEAL_DOCUMENTS/"
        )
    except Exception as e:
        logger.warning(f"Failed to restore seed DOCX files: {e}")


@app.post("/data/reset")
async def reset_demo(body: ResetRequest | None = None):
    if body and body.claim_ids:
        _reset_claims(body.claim_ids)
        logger.info(f"Selective reset completed for {body.claim_ids}")
        return {"status": "reset_complete", "mode": "selective", "claim_ids": body.claim_ids}

    _execute(f"DELETE FROM {DB}.{SCHEMA}.DENIAL_WORK_ITEMS WHERE CREATED_BY = 'DENIAL_AGENT'")
    _execute(f"DELETE FROM {DB}.{SCHEMA}.DENIAL_NOTES WHERE CREATED_BY = 'DENIAL_AGENT'")
    _execute(f"DELETE FROM {DB}.{SCHEMA}.APPEAL_DRAFTS WHERE CREATED_BY = 'DENIAL_AGENT'")
    _execute(f"UPDATE {DB}.{SCHEMA}.DENIALS SET PROCESSED_BY_AGENT = false, AGENT_RESULT = NULL, AGENT_PROCESSED_AT = NULL WHERE PROCESSED_BY_AGENT = true")
    try:
        _execute(f"REMOVE @{DB}.{SCHEMA}.APPEAL_DOCUMENTS")
    except Exception:
        pass

    mode = (body.mode if body else "seed") or "seed"
    if mode == "seed":
        _restore_seed()
        logger.info("Full reset — seed state restored (6 processed + 1 unprocessed)")
        return {"status": "reset_complete", "mode": "seed"}

    logger.info("Full reset — clean slate")
    return {"status": "reset_complete", "mode": "clean"}
