-- verify_pipeline.sql
-- Health check queries for the EDI parsing pipeline.
-- Run with: /edi:status

-- 1. Dynamic Table refresh status
SELECT
    NAME,
    STATE,
    STATE_MESSAGE,
    REFRESH_ACTION,
    DATA_TIMESTAMP,
    DATEDIFF('minute', DATA_TIMESTAMP, CURRENT_TIMESTAMP()) AS LAG_MINUTES
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY())
WHERE DATABASE_NAME = 'X12_EDI_AI'
ORDER BY DATA_TIMESTAMP DESC
LIMIT 20;

-- 2. Landing table row counts
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ROW_COUNT,
    ROUND(BYTES / 1024 / 1024, 2) AS SIZE_MB,
    LAST_ALTERED
FROM X12_EDI_AI.INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
  AND TABLE_NAME LIKE 'LANDING_%'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- 3. Task execution history (lite path)
SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 50
))
WHERE NAME LIKE '%EDI%'
ORDER BY SCHEDULED_TIME DESC;

-- 4. Network policy check (for SPCS auth issues)
SELECT
    CLIENT_IP,
    ERROR_CODE,
    ERROR_MESSAGE,
    EVENT_TIMESTAMP,
    USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO'
  AND EVENT_TIMESTAMP > DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND (ERROR_CODE = 390146 OR ERROR_MESSAGE LIKE '%network policy%')
ORDER BY EVENT_TIMESTAMP DESC
LIMIT 20;

-- 5. Dynamic Table current state
SHOW DYNAMIC TABLES IN DATABASE X12_EDI_AI;
