-- ============================================================
-- MULTI-TENANT PLATFORM: FOUNDATION SETUP
-- Run ONCE per Snowflake account before any tenant onboarding
-- Replace all {{VARIABLES}} with your actual values
-- ============================================================

-- =========================
-- GOVERNANCE DATABASE
-- =========================
CREATE DATABASE IF NOT EXISTS {{GOVERNANCE_DB}};
CREATE SCHEMA IF NOT EXISTS {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{GOVERNANCE_DB}}.{{TAG_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{GOVERNANCE_DB}}.{{AUDIT_SCHEMA}};

-- =========================
-- COST MANAGEMENT DATABASE
-- =========================
CREATE DATABASE IF NOT EXISTS {{COST_DB}};
CREATE SCHEMA IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{COST_DB}}.{{ANALYTICS_SCHEMA}};

-- =========================
-- PLATFORM ROLES
-- =========================
CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN_ROLE
    COMMENT = 'Top-level admin for multi-tenant platform';
GRANT ROLE PLATFORM_ADMIN_ROLE TO ROLE SYSADMIN;

CREATE ROLE IF NOT EXISTS FINOPS_ADMIN_ROLE
    COMMENT = 'FinOps team — cost attribution and budgeting';
GRANT ROLE FINOPS_ADMIN_ROLE TO ROLE SYSADMIN;

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
    COMMENT = 'Platform data engineering team';
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

CREATE ROLE IF NOT EXISTS GOVERNANCE_ADMIN_ROLE
    COMMENT = 'Governance team — policies, tags, classification';
GRANT ROLE GOVERNANCE_ADMIN_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

-- =========================
-- GOVERNANCE GRANTS
-- =========================
GRANT ALL ON DATABASE {{GOVERNANCE_DB}} TO ROLE GOVERNANCE_ADMIN_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE {{GOVERNANCE_DB}} TO ROLE GOVERNANCE_ADMIN_ROLE;

GRANT ALL ON DATABASE {{COST_DB}} TO ROLE FINOPS_ADMIN_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE {{COST_DB}} TO ROLE FINOPS_ADMIN_ROLE;

-- =========================
-- ENTITLEMENTS TABLE
-- =========================
CREATE TABLE IF NOT EXISTS {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.TENANT_ENTITLEMENTS (
    ROLE_NAME       VARCHAR NOT NULL,
    TENANT_ID       VARCHAR NOT NULL,
    ACCESS_LEVEL    VARCHAR DEFAULT 'READ',
    GRANTED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    GRANTED_BY      VARCHAR DEFAULT CURRENT_USER(),
    CONSTRAINT pk_entitlements PRIMARY KEY (ROLE_NAME, TENANT_ID)
);

-- =========================
-- ROW ACCESS POLICY
-- =========================
CREATE OR REPLACE ROW ACCESS POLICY {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.TENANT_ISOLATION_RAP
AS (tenant_id_col VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'PLATFORM_ADMIN_ROLE')
    OR tenant_id_col IN (
        SELECT TENANT_ID
        FROM {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.TENANT_ENTITLEMENTS
        WHERE ROLE_NAME = CURRENT_ROLE()
    );

-- =========================
-- MASKING POLICIES
-- =========================
CREATE OR REPLACE MASKING POLICY {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.SENSITIVE_FULL_MASK
AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'PLATFORM_ADMIN_ROLE')
        THEN val
        ELSE '***MASKED***'
    END;

CREATE OR REPLACE MASKING POLICY {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.SENSITIVE_PARTIAL_MASK
AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'PLATFORM_ADMIN_ROLE')
        THEN val
        ELSE CONCAT('***', RIGHT(val, 4))
    END;

CREATE OR REPLACE MASKING POLICY {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.DATE_MASK
AS (val DATE) RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN', 'PLATFORM_ADMIN_ROLE')
        THEN val
        ELSE DATE_TRUNC('YEAR', val)
    END;

-- =========================
-- GOVERNANCE TAGS
-- =========================
CREATE TAG IF NOT EXISTS {{GOVERNANCE_DB}}.{{TAG_SCHEMA}}.SENSITIVITY_LEVEL
    ALLOWED_VALUES 'FULL_MASK', 'PARTIAL_MASK', 'DATE_MASK', 'NONE'
    COMMENT = 'Data sensitivity level for tag-based masking';

CREATE TAG IF NOT EXISTS {{GOVERNANCE_DB}}.{{TAG_SCHEMA}}.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data classification level';

-- =========================
-- COST ATTRIBUTION TAGS
-- =========================
CREATE TAG IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_ID
    COMMENT = 'Tenant identifier for cost attribution';

CREATE TAG IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.COST_CENTER
    COMMENT = 'Cost center for financial attribution';

CREATE TAG IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.SERVICE_TIER
    ALLOWED_VALUES 'BASIC', 'STANDARD', 'PREMIUM', 'ENTERPRISE'
    COMMENT = 'Tenant service tier for pricing';

-- =========================
-- FINOPS CONFIGURATION TABLES
-- =========================
CREATE TABLE IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_REGISTRY (
    TENANT_ID           VARCHAR PRIMARY KEY,
    TENANT_NAME         VARCHAR NOT NULL,
    TENANT_TYPE         VARCHAR,
    CONTRACT_VALUE      NUMBER(12,2),
    CREDIT_RATE         NUMBER(6,4) DEFAULT 3.00,
    TENANCY_PATTERN     VARCHAR,
    SERVICE_TIER        VARCHAR DEFAULT 'STANDARD',
    ACTIVE              BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.WAREHOUSE_TENANT_MAP (
    WAREHOUSE_NAME  VARCHAR NOT NULL,
    TENANT_ID       VARCHAR,
    WAREHOUSE_TYPE  VARCHAR NOT NULL,
    CONSTRAINT pk_wh_map PRIMARY KEY (WAREHOUSE_NAME)
);

CREATE TABLE IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.TABLE_TENANT_RATIOS (
    RATIO_DATE           DATE NOT NULL,
    FULLY_QUALIFIED_NAME VARCHAR NOT NULL,
    TENANT_ID            VARCHAR NOT NULL,
    ROW_RATIO            FLOAT NOT NULL,
    ROW_COUNT            NUMBER,
    CONSTRAINT pk_ratios PRIMARY KEY (RATIO_DATE, FULLY_QUALIFIED_NAME, TENANT_ID)
);

CREATE TABLE IF NOT EXISTS {{COST_DB}}.{{FINOPS_SCHEMA}}.READER_SPONSOR_MAP (
    READER_ACCOUNT_NAME VARCHAR PRIMARY KEY,
    SPONSOR_TENANT_ID   VARCHAR NOT NULL,
    PARTNER_NAME        VARCHAR
);
