-- ============================================================
-- MULTI-TENANT PLATFORM: TENANT ONBOARDING
-- Replace {{VARIABLES}} before execution
-- ============================================================

-- =========================
-- MTT TENANT ONBOARDING
-- =========================
-- Prerequisites: Foundation setup complete, RLAP attached to shared tables

-- {{TENANT_ID}}       e.g., TENANT_ACME
-- {{TENANT_NAME}}     e.g., Acme Corporation
-- {{TENANT_TYPE}}     e.g., ENTERPRISE / SMB / PARTNER
-- {{DATA_DB}}         e.g., ACME_DATA
-- {{SHARED_SCHEMA}}   e.g., SHARED
-- {{SHARED_WH}}       e.g., PLATFORM_SHARED_WH
-- {{SERVICE_TIER}}    e.g., BASIC / STANDARD / PREMIUM / ENTERPRISE

-- 1. Tenant role
CREATE ROLE IF NOT EXISTS {{TENANT_ID}}_ROLE
    COMMENT = 'Tenant role for {{TENANT_NAME}}';
GRANT ROLE {{TENANT_ID}}_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

-- 2. Database and schema access
GRANT USAGE ON DATABASE {{DATA_DB}} TO ROLE {{TENANT_ID}}_ROLE;
GRANT USAGE ON SCHEMA {{DATA_DB}}.{{SHARED_SCHEMA}} TO ROLE {{TENANT_ID}}_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATA_DB}}.{{SHARED_SCHEMA}} TO ROLE {{TENANT_ID}}_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATA_DB}}.{{SHARED_SCHEMA}} TO ROLE {{TENANT_ID}}_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATA_DB}}.{{SHARED_SCHEMA}} TO ROLE {{TENANT_ID}}_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DATA_DB}}.{{SHARED_SCHEMA}} TO ROLE {{TENANT_ID}}_ROLE;

-- 3. Warehouse access
GRANT USAGE ON WAREHOUSE {{SHARED_WH}} TO ROLE {{TENANT_ID}}_ROLE;

-- 4. RLAP entitlement
INSERT INTO {{GOVERNANCE_DB}}.{{POLICY_SCHEMA}}.TENANT_ENTITLEMENTS (ROLE_NAME, TENANT_ID, ACCESS_LEVEL)
VALUES ('{{TENANT_ID}}_ROLE', '{{TENANT_ID}}', 'READ');

-- 5. FinOps registration
INSERT INTO {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_REGISTRY
    (TENANT_ID, TENANT_NAME, TENANT_TYPE, TENANCY_PATTERN, SERVICE_TIER)
VALUES ('{{TENANT_ID}}', '{{TENANT_NAME}}', '{{TENANT_TYPE}}', 'MTT', '{{SERVICE_TIER}}');

-- 6. Tenant user
CREATE USER IF NOT EXISTS {{TENANT_ID}}_ANALYST
    DEFAULT_ROLE = '{{TENANT_ID}}_ROLE'
    DEFAULT_WAREHOUSE = '{{SHARED_WH}}'
    MUST_CHANGE_PASSWORD = TRUE
    COMMENT = 'Primary analyst for {{TENANT_NAME}}';
GRANT ROLE {{TENANT_ID}}_ROLE TO USER {{TENANT_ID}}_ANALYST;

-- 7. Cost tagging
ALTER USER {{TENANT_ID}}_ANALYST SET TAG {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_ID = '{{TENANT_ID}}';


-- =========================
-- OPT TENANT ONBOARDING
-- =========================
-- {{TENANT_SCHEMA}}   e.g., SCHEMA_ACME
-- {{WH_SIZE}}         e.g., SMALL
-- {{CREDIT_QUOTA}}    e.g., 500

-- 1. Dedicated schema
CREATE SCHEMA IF NOT EXISTS {{DATA_DB}}.{{TENANT_SCHEMA}}
    COMMENT = 'Dedicated schema for {{TENANT_NAME}}';

-- 2. Dedicated warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_{{TENANT_ID}}
    WAREHOUSE_SIZE = '{{WH_SIZE}}'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    ENABLE_QUERY_ACCELERATION = TRUE
    COMMENT = 'Dedicated warehouse for {{TENANT_NAME}}';

-- 3. Role hierarchy
CREATE ROLE IF NOT EXISTS {{TENANT_ID}}_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS {{TENANT_ID}}_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS {{TENANT_ID}}_VIEWER_ROLE;
GRANT ROLE {{TENANT_ID}}_VIEWER_ROLE TO ROLE {{TENANT_ID}}_ANALYST_ROLE;
GRANT ROLE {{TENANT_ID}}_ANALYST_ROLE TO ROLE {{TENANT_ID}}_ADMIN_ROLE;
GRANT ROLE {{TENANT_ID}}_ADMIN_ROLE TO ROLE PLATFORM_ADMIN_ROLE;

-- 4. Permissions
GRANT USAGE ON DATABASE {{DATA_DB}} TO ROLE {{TENANT_ID}}_VIEWER_ROLE;
GRANT USAGE ON SCHEMA {{DATA_DB}}.{{TENANT_SCHEMA}} TO ROLE {{TENANT_ID}}_VIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATA_DB}}.{{TENANT_SCHEMA}} TO ROLE {{TENANT_ID}}_VIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATA_DB}}.{{TENANT_SCHEMA}} TO ROLE {{TENANT_ID}}_VIEWER_ROLE;
GRANT ALL ON SCHEMA {{DATA_DB}}.{{TENANT_SCHEMA}} TO ROLE {{TENANT_ID}}_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE WH_{{TENANT_ID}} TO ROLE {{TENANT_ID}}_VIEWER_ROLE;

-- 5. Resource monitor
CREATE RESOURCE MONITOR IF NOT EXISTS RM_{{TENANT_ID}}
    WITH CREDIT_QUOTA = {{CREDIT_QUOTA}}
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE WH_{{TENANT_ID}} SET RESOURCE_MONITOR = RM_{{TENANT_ID}};

-- 6. Cost tagging
ALTER WAREHOUSE WH_{{TENANT_ID}} SET TAG {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_ID = '{{TENANT_ID}}';
ALTER SCHEMA {{DATA_DB}}.{{TENANT_SCHEMA}} SET TAG {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_ID = '{{TENANT_ID}}';

-- 7. FinOps registration
INSERT INTO {{COST_DB}}.{{FINOPS_SCHEMA}}.TENANT_REGISTRY
    (TENANT_ID, TENANT_NAME, TENANT_TYPE, TENANCY_PATTERN, SERVICE_TIER)
VALUES ('{{TENANT_ID}}', '{{TENANT_NAME}}', '{{TENANT_TYPE}}', 'OPT', '{{SERVICE_TIER}}');

INSERT INTO {{COST_DB}}.{{FINOPS_SCHEMA}}.WAREHOUSE_TENANT_MAP (WAREHOUSE_NAME, TENANT_ID, WAREHOUSE_TYPE)
VALUES ('WH_{{TENANT_ID}}', '{{TENANT_ID}}', 'DEDICATED');
