-- =============================================================================
-- STEP 1: DATABASES, SCHEMAS, WAREHOUSE, COMPUTE POOL, IMAGE REPOSITORIES
-- Run this FIRST. Replace __PLACEHOLDERS__ by running scripts/configure.sh
-- =============================================================================

USE ROLE SYSADMIN;

-- 1. App database and schemas
CREATE DATABASE IF NOT EXISTS __APP_DATABASE__;
CREATE SCHEMA IF NOT EXISTS __APP_DATABASE__.__APP_SCHEMA__;
CREATE SCHEMA IF NOT EXISTS __APP_DATABASE__.SPCS;

-- 2. Platform database and schemas
CREATE DATABASE IF NOT EXISTS __PLATFORM_DATABASE__;
CREATE SCHEMA IF NOT EXISTS __PLATFORM_DATABASE__.SPCS;

-- 3. Warehouse
CREATE WAREHOUSE IF NOT EXISTS __WAREHOUSE__
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- 4. Compute pool for SPCS services
CREATE COMPUTE POOL IF NOT EXISTS __COMPUTE_POOL__
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_L
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300;

-- 5. Image repositories
CREATE IMAGE REPOSITORY IF NOT EXISTS __PLATFORM_DATABASE__.SPCS.CORTEX_CODE_REPO;
CREATE IMAGE REPOSITORY IF NOT EXISTS __APP_DATABASE__.SPCS.APP_IMAGE_REPO;

-- 6. Verify
SHOW IMAGE REPOSITORIES IN SCHEMA __PLATFORM_DATABASE__.SPCS;
SHOW IMAGE REPOSITORIES IN SCHEMA __APP_DATABASE__.SPCS;
