-- =============================================================================
-- STEP 2: TABLES AND CORE SEED DATA
-- Run AFTER 01_databases_and_roles.sql
-- All __PLACEHOLDERS__ are replaced by scripts/configure.sh
-- =============================================================================

USE ROLE SYSADMIN;
USE DATABASE __APP_DATABASE__;
USE SCHEMA __APP_SCHEMA__;
USE WAREHOUSE __WAREHOUSE__;

-- =============================================================================
-- CORE TABLES
-- =============================================================================

CREATE OR REPLACE TABLE MEMBERS (
    MEMBER_ID       VARCHAR(20) NOT NULL PRIMARY KEY,
    FIRST_NAME      VARCHAR(50),
    LAST_NAME       VARCHAR(50),
    DOB             DATE,
    GENDER          VARCHAR(1),
    SSN_LAST4       VARCHAR(4),
    ADDRESS         VARCHAR(200),
    CITY            VARCHAR(50),
    STATE           VARCHAR(2),
    ZIP             VARCHAR(10),
    PHONE           VARCHAR(15),
    PLAN_ID         VARCHAR(20),
    GROUP_NUMBER    VARCHAR(20),
    PAYER_ID        VARCHAR(20),
    EFFECTIVE_DATE  DATE,
    TERM_DATE       DATE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CLAIMS (
    CLAIM_ID              VARCHAR(20) NOT NULL PRIMARY KEY,
    MEMBER_ID             VARCHAR(20),
    PROVIDER_ID           VARCHAR(20),
    PROVIDER_NPI          VARCHAR(15),
    GROUP_NPI             VARCHAR(15),
    PROVIDER_NAME         VARCHAR(100),
    FACILITY_NAME         VARCHAR(100),
    PAYER_ID              VARCHAR(20),
    PLAN_ID               VARCHAR(20),
    DATE_OF_SERVICE       DATE,
    DATE_SUBMITTED        DATE,
    CLAIM_TYPE            VARCHAR(20),
    TOTAL_BILLED          NUMBER(12,2),
    TOTAL_ALLOWED         NUMBER(12,2),
    TOTAL_PAID            NUMBER(12,2),
    PATIENT_RESPONSIBILITY NUMBER(12,2),
    STATUS                VARCHAR(20),
    PRIMARY_DIAGNOSIS     VARCHAR(10),
    DIAGNOSIS_DESCRIPTION VARCHAR(200),
    PLACE_OF_SERVICE      VARCHAR(5),
    PRIOR_AUTH_ID         VARCHAR(20),
    PAYER_REF_NUMBER      VARCHAR(30),
    COB_INDICATOR         BOOLEAN DEFAULT FALSE,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CLAIM_LINES (
    LINE_ID         VARCHAR(25) NOT NULL PRIMARY KEY,
    CLAIM_ID        VARCHAR(20),
    LINE_NUMBER     NUMBER(38,0),
    CPT_CODE        VARCHAR(10),
    CPT_DESCRIPTION VARCHAR(200),
    MODIFIER        VARCHAR(10),
    DIAGNOSIS_ICD   VARCHAR(10),
    UNITS           NUMBER(38,0) DEFAULT 1,
    LINE_BILLED     NUMBER(12,2),
    LINE_ALLOWED    NUMBER(12,2),
    LINE_PAID       NUMBER(12,2),
    SERVICE_DATE    DATE,
    REVENUE_CODE    VARCHAR(10),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DENIALS (
    DENIAL_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    CLAIM_ID           VARCHAR(20),
    DENIAL_DATE        DATE,
    DENIAL_CODE        VARCHAR(10),
    DENIAL_GROUP       VARCHAR(5),
    DENIAL_REASON      VARCHAR(500),
    DENIAL_AMOUNT      NUMBER(12,2),
    PAYER_REMARK       VARCHAR(500),
    PROCESSED_BY_AGENT BOOLEAN DEFAULT FALSE,
    AGENT_PROCESSED_AT TIMESTAMP_NTZ,
    AGENT_RESULT       VARIANT,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ELIGIBILITY_BENEFITS (
    ELIG_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    MEMBER_ID        VARCHAR(20),
    PLAN_ID          VARCHAR(20),
    PAYER_ID         VARCHAR(20),
    EFFECTIVE_DATE   DATE,
    TERM_DATE        DATE,
    COVERAGE_STATUS  VARCHAR(20),
    PLAN_TYPE        VARCHAR(50),
    PLAN_NAME        VARCHAR(100),
    BENEFIT_CATEGORY VARCHAR(50),
    IN_NETWORK       BOOLEAN DEFAULT TRUE,
    COPAY            NUMBER(8,2),
    COINSURANCE      NUMBER(5,2),
    DEDUCTIBLE       NUMBER(10,2),
    DEDUCTIBLE_MET   NUMBER(10,2),
    OOP_MAX          NUMBER(10,2),
    OOP_MET          NUMBER(10,2),
    AUTH_REQUIRED    BOOLEAN DEFAULT FALSE,
    COB_PRIMARY      BOOLEAN DEFAULT TRUE,
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PRIOR_AUTH (
    AUTH_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    MEMBER_ID        VARCHAR(20),
    PROVIDER_ID      VARCHAR(20),
    PROVIDER_NPI     VARCHAR(15),
    GROUP_NPI        VARCHAR(15),
    PAYER_ID         VARCHAR(20),
    AUTH_STATUS      VARCHAR(20),
    AUTH_TYPE        VARCHAR(50),
    SERVICE_CATEGORY VARCHAR(50),
    CPT_CODES        VARCHAR(200),
    DIAGNOSIS_CODES  VARCHAR(200),
    VALID_FROM       DATE,
    VALID_TO         DATE,
    UNITS_APPROVED   NUMBER(38,0),
    UNITS_USED       NUMBER(38,0) DEFAULT 0,
    REQUESTED_DATE   DATE,
    DECISION_DATE    DATE,
    NOTES            VARCHAR(500),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CONTRACTS (
    CONTRACT_ID        VARCHAR(20) NOT NULL PRIMARY KEY,
    PAYER_ID           VARCHAR(20),
    PLAN_ID            VARCHAR(20),
    PROVIDER_GROUP     VARCHAR(50),
    EFFECTIVE_DATE     DATE,
    TERM_DATE          DATE,
    FILING_LIMIT_DAYS  NUMBER(38,0),
    APPEAL_WINDOW_DAYS NUMBER(38,0),
    TIMELY_FILING_DAYS NUMBER(38,0),
    AUTH_REQUIREMENTS  VARCHAR(500),
    COVERAGE_NOTES     VARCHAR(1000),
    RESUBMISSION_POLICY VARCHAR(500),
    NPI_POLICY         VARCHAR(500),
    SPECIAL_TERMS      VARCHAR(1000),
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- OPERATIONAL TABLES (written to by the agent)
-- =============================================================================

CREATE OR REPLACE TABLE DENIAL_WORK_ITEMS (
    WORK_ITEM_ID        VARCHAR(20) NOT NULL PRIMARY KEY,
    CLAIM_ID            VARCHAR(20),
    DENIAL_ID           VARCHAR(20),
    STATUS              VARCHAR(20) DEFAULT 'OPEN',
    QUEUE               VARCHAR(50),
    PRIORITY            VARCHAR(10),
    ASSIGNED_TO         VARCHAR(50),
    DUE_DATE            DATE,
    RESOLUTION_STRATEGY VARCHAR(50),
    RESOLUTION_NOTES    VARCHAR(1000),
    CREATED_BY          VARCHAR(50),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DENIAL_NOTES (
    NOTE_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    CLAIM_ID         VARCHAR(20),
    DENIAL_ID        VARCHAR(20),
    NOTE_TYPE        VARCHAR(20),
    NOTE_TEXT        VARCHAR(5000),
    EVIDENCE_SUMMARY VARCHAR(3000),
    CREATED_BY       VARCHAR(50),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE APPEAL_DRAFTS (
    APPEAL_ID        VARCHAR(20) NOT NULL PRIMARY KEY,
    CLAIM_ID         VARCHAR(20),
    DENIAL_ID        VARCHAR(20),
    APPEAL_TYPE      VARCHAR(30),
    APPEAL_BODY      VARCHAR(10000),
    POLICY_CITATIONS VARCHAR(2000),
    STATUS           VARCHAR(20) DEFAULT 'DRAFT',
    CREATED_BY       VARCHAR(50),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DOCX_STAGE_PATH  VARCHAR(16777216),
    REVIEW_STATUS    VARCHAR(16777216) DEFAULT 'DRAFT',
    REVIEWER_NOTES   VARCHAR(16777216),
    REVIEWED_AT      TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DENIAL_AGENT_AUDIT (
    AUDIT_ID    VARCHAR(30) NOT NULL PRIMARY KEY,
    SESSION_ID  VARCHAR(50),
    CLAIM_ID    VARCHAR(20),
    TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TOOL_NAME   VARCHAR(50),
    TOOL_INPUT  VARIANT,
    TOOL_OUTPUT VARIANT,
    DURATION_MS NUMBER(38,0),
    TRIGGER_TYPE VARCHAR(20)
);

CREATE OR REPLACE TABLE REMIT_835 (
    REMIT_ID          VARCHAR(20) NOT NULL PRIMARY KEY,
    CLAIM_ID          VARCHAR(20),
    PAYER_ID          VARCHAR(20),
    CHECK_NUMBER      VARCHAR(30),
    PAYMENT_DATE      DATE,
    TOTAL_CHARGE      NUMBER(12,2),
    TOTAL_PAID        NUMBER(12,2),
    PATIENT_RESP      NUMBER(12,2),
    ADJUSTMENT_AMOUNT NUMBER(12,2),
    REMARK_CODES      VARCHAR(200),
    CARC_CODE         VARCHAR(10),
    RARC_CODE         VARCHAR(10),
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- PAYER POLICY DOCUMENTS (source for Cortex Search)
-- =============================================================================

CREATE OR REPLACE TABLE PAYER_DOCS (
    DOC_ID         VARCHAR(20) NOT NULL PRIMARY KEY,
    PAYER_ID       VARCHAR(20),
    PAYER_NAME     VARCHAR(100),
    DOC_TYPE       VARCHAR(50),
    DOC_TITLE      VARCHAR(200),
    SECTION_NUMBER VARCHAR(20),
    SECTION_TITLE  VARCHAR(200),
    CONTENT        VARCHAR(5000),
    EFFECTIVE_DATE DATE,
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================================================
-- SEED STATE TABLES (used by demo reset functionality)
-- =============================================================================

CREATE OR REPLACE TABLE SEED_DENIALS (
    DENIAL_ID          VARCHAR(20),
    CLAIM_ID           VARCHAR(20),
    DENIAL_DATE        DATE,
    DENIAL_CODE        VARCHAR(10),
    DENIAL_GROUP       VARCHAR(5),
    DENIAL_REASON      VARCHAR(500),
    DENIAL_AMOUNT      NUMBER(12,2),
    PAYER_REMARK       VARCHAR(500),
    PROCESSED_BY_AGENT BOOLEAN DEFAULT FALSE,
    AGENT_PROCESSED_AT TIMESTAMP_NTZ,
    AGENT_RESULT       VARIANT,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SEED_DENIALS_AGENT_STATE (
    DENIAL_ID          VARCHAR(20),
    CLAIM_ID           VARCHAR(20),
    AGENT_RESULT       VARIANT,
    AGENT_PROCESSED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SEED_DENIAL_WORK_ITEMS (
    WORK_ITEM_ID        VARCHAR(20),
    CLAIM_ID            VARCHAR(20),
    DENIAL_ID           VARCHAR(20),
    STATUS              VARCHAR(20),
    QUEUE               VARCHAR(50),
    PRIORITY            VARCHAR(10),
    ASSIGNED_TO         VARCHAR(50),
    DUE_DATE            DATE,
    RESOLUTION_STRATEGY VARCHAR(50),
    RESOLUTION_NOTES    VARCHAR(1000),
    CREATED_BY          VARCHAR(50),
    CREATED_AT          TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SEED_WORK_ITEMS (LIKE SEED_DENIAL_WORK_ITEMS);

CREATE OR REPLACE TABLE SEED_DENIAL_NOTES (
    NOTE_ID          VARCHAR(20),
    CLAIM_ID         VARCHAR(20),
    DENIAL_ID        VARCHAR(20),
    NOTE_TYPE        VARCHAR(20),
    NOTE_TEXT        VARCHAR(5000),
    EVIDENCE_SUMMARY VARCHAR(3000),
    CREATED_BY       VARCHAR(50),
    CREATED_AT       TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE SEED_NOTES (LIKE SEED_DENIAL_NOTES);

CREATE OR REPLACE TABLE SEED_APPEAL_DRAFTS (
    APPEAL_ID        VARCHAR(20),
    CLAIM_ID         VARCHAR(20),
    DENIAL_ID        VARCHAR(20),
    APPEAL_TYPE      VARCHAR(30),
    APPEAL_BODY      VARCHAR(10000),
    POLICY_CITATIONS VARCHAR(2000),
    STATUS           VARCHAR(20),
    CREATED_BY       VARCHAR(50),
    CREATED_AT       TIMESTAMP_NTZ,
    DOCX_STAGE_PATH  VARCHAR(16777216),
    REVIEW_STATUS    VARCHAR(16777216),
    REVIEWER_NOTES   VARCHAR(16777216),
    REVIEWED_AT      TIMESTAMP_NTZ
);

-- =============================================================================
-- STAGES
-- =============================================================================

CREATE STAGE IF NOT EXISTS APPEAL_DOCUMENTS
    COMMENT = 'Internal stage for AI-generated appeal letter DOCX files';

CREATE STAGE IF NOT EXISTS MODELS
    COMMENT = 'Internal stage for Cortex Analyst semantic model YAML files';
