-- =============================================================================
-- TEARDOWN — Complete cleanup
-- Drops ALL objects created by this solution.
-- WARNING: This is destructive and cannot be undone.
-- =============================================================================

USE ROLE SYSADMIN;

-- 1. Stop and drop services
ALTER SERVICE IF EXISTS __APP_DATABASE__.SPCS.DENIED_CLAIMS_APP SUSPEND;
DROP SERVICE IF EXISTS __APP_DATABASE__.SPCS.DENIED_CLAIMS_APP;

ALTER SERVICE IF EXISTS __PLATFORM_DATABASE__.SPCS.CORTEX_CODE_SERVICE SUSPEND;
DROP SERVICE IF EXISTS __PLATFORM_DATABASE__.SPCS.CORTEX_CODE_SERVICE;

-- 2. Drop task
ALTER TASK IF EXISTS __APP_DATABASE__.__APP_SCHEMA__.DENIAL_MONITOR SUSPEND;
DROP TASK IF EXISTS __APP_DATABASE__.__APP_SCHEMA__.DENIAL_MONITOR;

-- 3. Drop service function
DROP FUNCTION IF EXISTS __APP_DATABASE__.__APP_SCHEMA__.PROCESS_DENIED_CLAIM(VARCHAR);

-- 4. Drop external access integrations
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS DENIED_CLAIMS_APP_EAI;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS CORTEX_CODE_EXTERNAL_ACCESS;

-- 5. Drop network rules
DROP NETWORK RULE IF EXISTS __APP_DATABASE__.SPCS.CORTEX_CODE_API_EGRESS;
DROP NETWORK RULE IF EXISTS __APP_DATABASE__.SPCS.CORTEX_API_EGRESS;
DROP NETWORK RULE IF EXISTS __PLATFORM_DATABASE__.SPCS.CORTEX_CODE_OUTBOUND;

-- 6. Drop secrets
DROP SECRET IF EXISTS __APP_DATABASE__.SPCS.CORTEX_CODE_PAT;

-- 7. Drop Cortex services
DROP CORTEX SEARCH SERVICE IF EXISTS __APP_DATABASE__.__APP_SCHEMA__.PAYER_DOC_SEARCH;
DROP SEMANTIC VIEW IF EXISTS __APP_DATABASE__.__APP_SCHEMA__.DENIED_CLAIMS_AGENT_SV;

-- 8. Drop image repositories
DROP IMAGE REPOSITORY IF EXISTS __APP_DATABASE__.SPCS.APP_IMAGE_REPO;
DROP IMAGE REPOSITORY IF EXISTS __PLATFORM_DATABASE__.SPCS.CORTEX_CODE_REPO;

-- 9. Drop compute pool
DROP COMPUTE POOL IF EXISTS __COMPUTE_POOL__;

-- 10. Drop databases (this drops all schemas, tables, stages within)
DROP DATABASE IF EXISTS __APP_DATABASE__;
DROP DATABASE IF EXISTS __PLATFORM_DATABASE__;

-- 11. Drop warehouse (optional — comment out if shared)
-- DROP WAREHOUSE IF EXISTS __WAREHOUSE__;
