USE SCHEMA UNSTRUCTURED_HEALTHDATA.CLINICAL_NLP;

CREATE OR REPLACE PROCEDURE SP_RUN_PIPELINE(BATCH_SIZE INT DEFAULT 500, SAMPLE_LIMIT INT DEFAULT NULL)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id VARCHAR;
BEGIN
    v_run_id := 'PIPELINE-' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD-HH24MISS');

    INSERT INTO PIPELINE_RUN_LOG
    SELECT :v_run_id, 'PIPELINE_MASTER', 0, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL,
           OBJECT_CONSTRUCT('batch_size', :BATCH_SIZE, 'sample_limit', :SAMPLE_LIMIT);

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_1_CONDITIONS', 1, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_CONDITIONS(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_1_CONDITIONS';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_2_THERAPEUTICS', 2, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_THERAPEUTICS(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_2_THERAPEUTICS';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_3_OBSERVATIONS', 3, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_OBSERVATIONS(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_3_OBSERVATIONS';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_4_PATIENT_CONTEXT', 4, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_PATIENT_CONTEXT(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_4_PATIENT_CONTEXT';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_5_ONCOLOGY', 5, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_ONCOLOGY(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_5_ONCOLOGY';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_6_SAFETY_CARE', 6, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_EXTRACT_SAFETY_CARE(:BATCH_SIZE, :SAMPLE_LIMIT);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_6_SAFETY_CARE';

    INSERT INTO PIPELINE_RUN_LOG SELECT :v_run_id, 'STEP_7_NORMALIZATION', 7, 'RUNNING', CURRENT_TIMESTAMP(), NULL, 0, 0, NULL, NULL, NULL, NULL;
    CALL SP_NORMALIZE_ENTITIES(:BATCH_SIZE);
    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'STEP_7_NORMALIZATION';

    UPDATE PIPELINE_RUN_LOG SET status = 'COMPLETED', completed_at = CURRENT_TIMESTAMP() WHERE run_id = :v_run_id AND step_name = 'PIPELINE_MASTER';
    RETURN 'Pipeline complete. Run ID: ' || v_run_id;
END;
$$;

CREATE OR REPLACE VIEW PIPELINE_PROGRESS AS
SELECT run_id, step_name, step_order, status, started_at, completed_at,
    DATEDIFF('second', started_at, COALESCE(completed_at, CURRENT_TIMESTAMP())) AS elapsed_seconds,
    rows_processed, rows_inserted, batch_number, batch_size, metadata
FROM PIPELINE_RUN_LOG
ORDER BY run_id DESC, step_order, batch_number NULLS FIRST;

CREATE OR REPLACE VIEW ENTITY_COUNTS AS
SELECT 'CONDITION' AS entity_type, COUNT(*) AS total_rows, COUNT(code) AS coded_rows, ROUND(COUNT(code)*100.0/NULLIF(COUNT(*),0),1) AS coding_pct FROM CONDITION WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'MEDICATION_REQUEST', COUNT(*), COUNT(medication_code), ROUND(COUNT(medication_code)*100.0/NULLIF(COUNT(*),0),1) FROM MEDICATION_REQUEST WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'PROCEDURE', COUNT(*), COUNT(code), ROUND(COUNT(code)*100.0/NULLIF(COUNT(*),0),1) FROM "PROCEDURE" WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'OBSERVATION', COUNT(*), COUNT(code), ROUND(COUNT(code)*100.0/NULLIF(COUNT(*),0),1) FROM OBSERVATION WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'ALLERGY_INTOLERANCE', COUNT(*), COUNT(substance_code), ROUND(COUNT(substance_code)*100.0/NULLIF(COUNT(*),0),1) FROM ALLERGY_INTOLERANCE WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'ADVERSE_EVENT', COUNT(*), COUNT(event_code), ROUND(COUNT(event_code)*100.0/NULLIF(COUNT(*),0),1) FROM ADVERSE_EVENT WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'SOCIAL_HISTORY', COUNT(*), COUNT(code), ROUND(COUNT(code)*100.0/NULLIF(COUNT(*),0),1) FROM SOCIAL_HISTORY_OBSERVATION WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'FAMILY_HISTORY', COUNT(*), COUNT(condition_code), ROUND(COUNT(condition_code)*100.0/NULLIF(COUNT(*),0),1) FROM FAMILY_MEMBER_HISTORY WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'CARE_PLAN_ITEM', COUNT(*), NULL, NULL FROM CARE_PLAN_ITEM WHERE source = 'GENAI_NLP_NOTE'
UNION ALL SELECT 'TUMOR_EPISODE', COUNT(*), COUNT(histology_code), ROUND(COUNT(histology_code)*100.0/NULLIF(COUNT(*),0),1) FROM TUMOR_EPISODE WHERE source = 'GENAI_NLP_NOTE';

-- ============================================================
-- SCHEDULED TASK (optional production use)
-- ============================================================
-- CREATE OR REPLACE TASK TASK_RUN_CLINICAL_NLP_PIPELINE
--     WAREHOUSE = BI_WH
--     SCHEDULE = 'USING CRON 0 2 * * * America/Los_Angeles'
-- AS
--     CALL SP_RUN_PIPELINE(500, NULL);
-- ALTER TASK TASK_RUN_CLINICAL_NLP_PIPELINE RESUME;
