-- =============================================================================
-- DICOM Ingestion: Cascading Dynamic Tables
-- Cascade: Patient -> Study -> Series -> Instance -> Equipment
-- Database: {database}.{schema}
-- =============================================================================

-- DT_DICOM_PATIENTS (Level 1)
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_PATIENTS
    TARGET_LAG = '10 minutes' WAREHOUSE = {warehouse}
AS
SELECT
    HASH(COALESCE(METADATA:PatientID::STRING, 'UNKNOWN'),
         COALESCE(METADATA:IssuerOfPatientID::STRING, '')) AS PATIENT_KEY,
    METADATA:PatientID::STRING AS PATIENT_ID,
    METADATA:IssuerOfPatientID::STRING AS ISSUER_OF_PATIENT_ID,
    METADATA:PatientName::STRING AS PATIENT_NAME,
    METADATA:PatientSex::STRING AS PATIENT_SEX,
    TRY_TO_DATE(METADATA:PatientBirthDate::STRING, 'YYYYMMDD') AS PATIENT_BIRTH_DATE,
    MAX(INGESTED_AT) AS _LOADED_AT
FROM {database}.{schema}.DICOM_RAW
WHERE METADATA:PatientID IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6;

-- DT_DICOM_STUDIES (Level 2 — joins DT_DICOM_PATIENTS)
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_STUDIES
    TARGET_LAG = '10 minutes' WAREHOUSE = {warehouse}
AS
SELECT
    HASH(r.METADATA:StudyInstanceUID::STRING) AS STUDY_KEY,
    p.PATIENT_KEY,
    r.METADATA:StudyInstanceUID::STRING AS STUDY_INSTANCE_UID,
    r.METADATA:AccessionNumber::STRING AS ACCESSION_NUMBER,
    TRY_TO_DATE(r.METADATA:StudyDate::STRING, 'YYYYMMDD') AS STUDY_DATE,
    r.METADATA:StudyDescription::STRING AS STUDY_DESCRIPTION,
    r.METADATA:ReferringPhysicianName::STRING AS REFERRING_PHYSICIAN,
    COUNT(DISTINCT r.METADATA:SeriesInstanceUID::STRING) AS NUMBER_OF_SERIES,
    COUNT(DISTINCT r.METADATA:SOPInstanceUID::STRING) AS NUMBER_OF_INSTANCES,
    ARRAY_UNIQUE_AGG(r.METADATA:Modality::STRING) AS MODALITIES_IN_STUDY,
    MAX(r.INGESTED_AT) AS _LOADED_AT
FROM {database}.{schema}.DICOM_RAW r
LEFT JOIN {database}.{schema}.DT_DICOM_PATIENTS p
    ON COALESCE(r.METADATA:PatientID::STRING, 'UNKNOWN') = p.PATIENT_ID
WHERE r.METADATA:StudyInstanceUID IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6, 7;

-- DT_DICOM_SERIES (Level 3 — joins DT_DICOM_STUDIES)
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_SERIES
    TARGET_LAG = '10 minutes' WAREHOUSE = {warehouse}
AS
SELECT
    HASH(r.METADATA:SeriesInstanceUID::STRING) AS SERIES_KEY,
    s.STUDY_KEY,
    r.METADATA:SeriesInstanceUID::STRING AS SERIES_INSTANCE_UID,
    r.METADATA:Modality::STRING AS MODALITY,
    r.METADATA:BodyPartExamined::STRING AS BODY_PART_EXAMINED,
    r.METADATA:SeriesDescription::STRING AS SERIES_DESCRIPTION,
    r.METADATA:ProtocolName::STRING AS PROTOCOL_NAME,
    COUNT(DISTINCT r.METADATA:SOPInstanceUID::STRING) AS NUMBER_OF_INSTANCES,
    MAX(r.INGESTED_AT) AS _LOADED_AT
FROM {database}.{schema}.DICOM_RAW r
LEFT JOIN {database}.{schema}.DT_DICOM_STUDIES s
    ON r.METADATA:StudyInstanceUID::STRING = s.STUDY_INSTANCE_UID
WHERE r.METADATA:SeriesInstanceUID IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6, 7;

-- DT_DICOM_INSTANCES (Level 4 — joins DT_DICOM_SERIES)
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_INSTANCES
    TARGET_LAG = '10 minutes' WAREHOUSE = {warehouse}
AS
SELECT
    HASH(r.METADATA:SOPInstanceUID::STRING) AS INSTANCE_KEY,
    ser.SERIES_KEY,
    r.METADATA:SOPInstanceUID::STRING AS SOP_INSTANCE_UID,
    r.METADATA:SOPClassUID::STRING AS SOP_CLASS_UID,
    TRY_TO_NUMBER(r.METADATA:InstanceNumber::STRING) AS INSTANCE_NUMBER,
    TRY_TO_NUMBER(r.METADATA:NumberOfFrames::STRING) AS NUMBER_OF_FRAMES,
    r.FILE_PATH, r.METADATA:TransferSyntaxUID::STRING AS TRANSFER_SYNTAX_UID,
    r.INGESTED_AT AS _LOADED_AT
FROM {database}.{schema}.DICOM_RAW r
LEFT JOIN {database}.{schema}.DT_DICOM_SERIES ser
    ON r.METADATA:SeriesInstanceUID::STRING = ser.SERIES_INSTANCE_UID
WHERE r.METADATA:SOPInstanceUID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY r.METADATA:SOPInstanceUID::STRING ORDER BY r.INGESTED_AT DESC) = 1;

-- DT_DICOM_EQUIPMENT (Level 3 — joins DT_DICOM_SERIES)
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_EQUIPMENT
    TARGET_LAG = '30 minutes' WAREHOUSE = {warehouse}
AS
SELECT
    HASH(ser.SERIES_KEY, COALESCE(r.METADATA:DeviceSerialNumber::STRING, '')) AS EQUIPMENT_KEY,
    ser.SERIES_KEY,
    r.METADATA:Manufacturer::STRING AS MANUFACTURER,
    r.METADATA:ManufacturerModelName::STRING AS MANUFACTURER_MODEL_NAME,
    r.METADATA:DeviceSerialNumber::STRING AS DEVICE_SERIAL_NUMBER,
    r.METADATA:InstitutionName::STRING AS INSTITUTION_NAME,
    r.METADATA:StationName::STRING AS STATION_NAME,
    MAX(r.INGESTED_AT) AS _LOADED_AT
FROM {database}.{schema}.DICOM_RAW r
LEFT JOIN {database}.{schema}.DT_DICOM_SERIES ser ON r.METADATA:SeriesInstanceUID::STRING = ser.SERIES_INSTANCE_UID
WHERE r.METADATA:Manufacturer IS NOT NULL OR r.METADATA:StationName IS NOT NULL
GROUP BY 1, 2, 3, 4, 5, 6, 7;

-- DT_DICOM_VALIDATION_SUMMARY
CREATE OR REPLACE DYNAMIC TABLE {database}.{schema}.DT_DICOM_VALIDATION_SUMMARY
    TARGET_LAG = '30 minutes' WAREHOUSE = {warehouse}
AS
SELECT CURRENT_TIMESTAMP() AS CHECKED_AT,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_STUDIES WHERE PATIENT_KEY IS NULL) AS ORPHANED_STUDIES,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_SERIES WHERE STUDY_KEY IS NULL) AS ORPHANED_SERIES,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_INSTANCES WHERE SERIES_KEY IS NULL) AS ORPHANED_INSTANCES,
    (SELECT COUNT(*) FROM {database}.{schema}.DICOM_INGESTION_ERRORS WHERE RESOLVED_AT IS NULL) AS UNRESOLVED_ERRORS,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_PATIENTS) AS TOTAL_PATIENTS,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_STUDIES) AS TOTAL_STUDIES,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_SERIES) AS TOTAL_SERIES,
    (SELECT COUNT(*) FROM {database}.{schema}.DT_DICOM_INSTANCES) AS TOTAL_INSTANCES;
