-- =============================================================================
-- DICOM Ingestion: Stream/Task Orchestration, Snowpipe, Error Handling, CDC
-- Database: {database}.{schema}
-- =============================================================================

-- ===== SNOWPIPE AUTO-INGEST =====

CREATE OR REPLACE PIPE {database}.{schema}.DICOM_INGEST_PIPE AUTO_INGEST = TRUE
    AWS_SNS_TOPIC = 'arn:aws:sns:us-west-2:123456789:dicom-notifications'
AS
COPY INTO {database}.{schema}.DICOM_RAW (FILE_PATH, METADATA)
FROM (SELECT METADATA$FILENAME, $1 FROM @{database}.{schema}.DICOM_EXTERNAL_STAGE)
FILE_FORMAT = {database}.{schema}.DICOM_JSON_FORMAT ON_ERROR = 'CONTINUE';

-- For Azure: INTEGRATION = 'AZURE_EVENT_NOTIFICATION'
-- For GCS: INTEGRATION = 'GCS_PUB_SUB_NOTIFICATION'

-- ===== STREAM + TASK TREE =====

CREATE OR REPLACE STREAM {database}.{schema}.DICOM_RAW_STREAM ON TABLE {database}.{schema}.DICOM_RAW APPEND_ONLY = TRUE;

-- Root task: Patient MERGE
CREATE OR REPLACE TASK {database}.{schema}.TASK_PROCESS_DICOM_PATIENTS
    WAREHOUSE = {warehouse} SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('{database}.{schema}.DICOM_RAW_STREAM')
AS
MERGE INTO {database}.{schema}.DICOM_PATIENT tgt USING (
    SELECT DISTINCT METADATA:PatientID::STRING AS PID,
        METADATA:IssuerOfPatientID::STRING AS ISSUER,
        METADATA:PatientName::STRING AS PNAME,
        METADATA:PatientSex::STRING AS PSEX,
        TRY_TO_DATE(METADATA:PatientBirthDate::STRING, 'YYYYMMDD') AS DOB
    FROM {database}.{schema}.DICOM_RAW_STREAM WHERE METADATA:PatientID IS NOT NULL
) src ON tgt.PATIENT_ID = src.PID AND COALESCE(tgt.ISSUER_OF_PATIENT_ID,'') = COALESCE(src.ISSUER,'')
WHEN NOT MATCHED THEN INSERT (SOURCE_SYSTEM, PATIENT_ID, ISSUER_OF_PATIENT_ID, PATIENT_NAME, PATIENT_SEX, PATIENT_BIRTH_DATE)
    VALUES ('PACS', src.PID, src.ISSUER, src.PNAME, src.PSEX, src.DOB)
WHEN MATCHED THEN UPDATE SET tgt.PATIENT_NAME = COALESCE(src.PNAME, tgt.PATIENT_NAME), tgt._LOADED_AT = CURRENT_TIMESTAMP();

-- Child task: Study MERGE
CREATE OR REPLACE TASK {database}.{schema}.TASK_PROCESS_DICOM_STUDIES
    WAREHOUSE = {warehouse} AFTER {database}.{schema}.TASK_PROCESS_DICOM_PATIENTS
AS
MERGE INTO {database}.{schema}.DICOM_STUDY tgt USING (
    SELECT DISTINCT p.PATIENT_KEY, r.METADATA:StudyInstanceUID::STRING AS SUID,
        r.METADATA:AccessionNumber::STRING AS ACC,
        TRY_TO_DATE(r.METADATA:StudyDate::STRING, 'YYYYMMDD') AS SDATE,
        r.METADATA:StudyDescription::STRING AS SDESC
    FROM {database}.{schema}.DICOM_RAW r JOIN {database}.{schema}.DICOM_PATIENT p ON r.METADATA:PatientID::STRING = p.PATIENT_ID
    WHERE r.INGESTED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP()) AND r.METADATA:StudyInstanceUID IS NOT NULL
) src ON tgt.STUDY_INSTANCE_UID = src.SUID
WHEN NOT MATCHED THEN INSERT (PATIENT_KEY, STUDY_INSTANCE_UID, ACCESSION_NUMBER, STUDY_DATE, STUDY_DESCRIPTION)
    VALUES (src.PATIENT_KEY, src.SUID, src.ACC, src.SDATE, src.SDESC)
WHEN MATCHED THEN UPDATE SET tgt.STUDY_DESCRIPTION = COALESCE(src.SDESC, tgt.STUDY_DESCRIPTION), tgt._LOADED_AT = CURRENT_TIMESTAMP();

-- Child task: Series MERGE
CREATE OR REPLACE TASK {database}.{schema}.TASK_PROCESS_DICOM_SERIES
    WAREHOUSE = {warehouse} AFTER {database}.{schema}.TASK_PROCESS_DICOM_STUDIES
AS
MERGE INTO {database}.{schema}.DICOM_SERIES tgt USING (
    SELECT DISTINCT s.STUDY_KEY, r.METADATA:SeriesInstanceUID::STRING AS SEUID,
        r.METADATA:Modality::STRING AS MOD, r.METADATA:BodyPartExamined::STRING AS BP,
        r.METADATA:SeriesDescription::STRING AS SDESC
    FROM {database}.{schema}.DICOM_RAW r JOIN {database}.{schema}.DICOM_STUDY s ON r.METADATA:StudyInstanceUID::STRING = s.STUDY_INSTANCE_UID
    WHERE r.INGESTED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP()) AND r.METADATA:SeriesInstanceUID IS NOT NULL
) src ON tgt.SERIES_INSTANCE_UID = src.SEUID
WHEN NOT MATCHED THEN INSERT (STUDY_KEY, SERIES_INSTANCE_UID, MODALITY, BODY_PART_EXAMINED, SERIES_DESCRIPTION)
    VALUES (src.STUDY_KEY, src.SEUID, src.MOD, src.BP, src.SDESC)
WHEN MATCHED THEN UPDATE SET tgt._LOADED_AT = CURRENT_TIMESTAMP();

-- Error routing task
CREATE OR REPLACE TASK {database}.{schema}.TASK_ROUTE_INGESTION_ERRORS
    WAREHOUSE = {warehouse} AFTER {database}.{schema}.TASK_PROCESS_DICOM_PATIENTS
AS
INSERT INTO {database}.{schema}.DICOM_INGESTION_ERRORS (RAW_KEY, FILE_PATH, ERROR_CATEGORY, ERROR_DETAIL, RAW_METADATA)
SELECT RAW_KEY, FILE_PATH,
    CASE WHEN METADATA IS NULL THEN 'PARSE_ERROR'
         WHEN METADATA:PatientID IS NULL AND METADATA:StudyInstanceUID IS NULL THEN 'VALIDATION_ERROR'
         ELSE 'UNKNOWN' END,
    CASE WHEN METADATA IS NULL THEN 'Failed to parse VARIANT'
         WHEN METADATA:PatientID IS NULL THEN 'Missing PatientID'
         ELSE 'Unclassified' END,
    METADATA
FROM {database}.{schema}.DICOM_RAW WHERE INGESTED_AT >= DATEADD(MINUTE, -10, CURRENT_TIMESTAMP())
  AND (METADATA IS NULL OR METADATA:PatientID IS NULL OR METADATA:StudyInstanceUID IS NULL);

-- ===== ERROR / DEAD LETTER TABLE =====

CREATE OR REPLACE TABLE {database}.{schema}.DICOM_INGESTION_ERRORS (
    ERROR_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    RAW_KEY NUMBER, FILE_PATH VARCHAR,
    ERROR_CATEGORY VARCHAR NOT NULL,
    ERROR_DETAIL VARCHAR, RAW_METADATA VARIANT,
    RETRY_COUNT NUMBER DEFAULT 0, MAX_RETRIES NUMBER DEFAULT 3,
    RESOLVED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ===== CDC PATTERN: Study Amendment Upsert =====

MERGE INTO {database}.{schema}.DICOM_STUDY tgt USING (
    SELECT METADATA:StudyInstanceUID::STRING AS SUID,
        METADATA:StudyDescription::STRING AS SDESC,
        COUNT(DISTINCT METADATA:SeriesInstanceUID::STRING) AS NSERIES,
        COUNT(DISTINCT METADATA:SOPInstanceUID::STRING) AS NINST
    FROM {database}.{schema}.DICOM_RAW WHERE INGESTED_AT >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP())
      AND METADATA:StudyInstanceUID IS NOT NULL GROUP BY 1, 2
) src ON tgt.STUDY_INSTANCE_UID = src.SUID
WHEN MATCHED AND (tgt.NUMBER_OF_SERIES < src.NSERIES OR tgt.NUMBER_OF_INSTANCES < src.NINST) THEN UPDATE SET
    tgt.STUDY_DESCRIPTION = src.SDESC,
    tgt.NUMBER_OF_SERIES = GREATEST(tgt.NUMBER_OF_SERIES, src.NSERIES),
    tgt.NUMBER_OF_INSTANCES = GREATEST(tgt.NUMBER_OF_INSTANCES, src.NINST),
    tgt._LOADED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (STUDY_INSTANCE_UID, STUDY_DESCRIPTION, NUMBER_OF_SERIES, NUMBER_OF_INSTANCES)
    VALUES (src.SUID, src.SDESC, src.NSERIES, src.NINST);

-- ===== VALIDATION QUERIES =====

-- Referential integrity
SELECT 'Orphaned Studies' AS CHECK_NAME, COUNT(*) AS COUNT FROM {database}.{schema}.DT_DICOM_STUDIES WHERE PATIENT_KEY IS NULL
UNION ALL
SELECT 'Orphaned Series', COUNT(*) FROM {database}.{schema}.DT_DICOM_SERIES WHERE STUDY_KEY IS NULL
UNION ALL
SELECT 'Orphaned Instances', COUNT(*) FROM {database}.{schema}.DT_DICOM_INSTANCES WHERE SERIES_KEY IS NULL;

-- Completeness scoring
SELECT METADATA:StudyInstanceUID::STRING AS STUDY_UID,
    (CASE WHEN METADATA:PatientID IS NOT NULL THEN 1 ELSE 0 END
     + CASE WHEN METADATA:StudyDate IS NOT NULL THEN 1 ELSE 0 END
     + CASE WHEN METADATA:Modality IS NOT NULL THEN 1 ELSE 0 END
     + CASE WHEN METADATA:SeriesInstanceUID IS NOT NULL THEN 1 ELSE 0 END
     + CASE WHEN METADATA:SOPInstanceUID IS NOT NULL THEN 1 ELSE 0 END
     + CASE WHEN METADATA:AccessionNumber IS NOT NULL THEN 1 ELSE 0 END
    ) / 6.0 AS COMPLETENESS_SCORE
FROM {database}.{schema}.DICOM_RAW
QUALIFY ROW_NUMBER() OVER (PARTITION BY METADATA:StudyInstanceUID::STRING ORDER BY INGESTED_AT DESC) = 1;

-- Cross-table consistency
SELECT 'PATIENTS' AS ENTITY, COUNT(*) AS DT_COUNT,
       (SELECT COUNT(DISTINCT METADATA:PatientID::STRING) FROM {database}.{schema}.DICOM_RAW) AS RAW_COUNT FROM {database}.{schema}.DT_DICOM_PATIENTS
UNION ALL SELECT 'STUDIES', COUNT(*), (SELECT COUNT(DISTINCT METADATA:StudyInstanceUID::STRING) FROM {database}.{schema}.DICOM_RAW) FROM {database}.{schema}.DT_DICOM_STUDIES
UNION ALL SELECT 'SERIES', COUNT(*), (SELECT COUNT(DISTINCT METADATA:SeriesInstanceUID::STRING) FROM {database}.{schema}.DICOM_RAW) FROM {database}.{schema}.DT_DICOM_SERIES
UNION ALL SELECT 'INSTANCES', COUNT(*), (SELECT COUNT(DISTINCT METADATA:SOPInstanceUID::STRING) FROM {database}.{schema}.DICOM_RAW) FROM {database}.{schema}.DT_DICOM_INSTANCES;
