#!/usr/bin/env python3
"""Generate a formatted DOCX appeal letter and upload to Snowflake stage."""

import argparse
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def create_appeal_docx(
    claim_id: str,
    denial_id: str,
    provider_name: str,
    provider_npi: str,
    member_name: str,
    member_id: str,
    plan_id: str,
    dos: str,
    denial_code: str,
    denial_reason: str,
    appeal_body: str,
    policy_citations: str,
    output_path: str,
):
    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)
    font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    draft = doc.add_paragraph()
    draft.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = draft.add_run("DRAFT — GENERATED BY AI AGENT")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)
    run.bold = True

    header_para = doc.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    header_para.space_after = Pt(4)
    run = header_para.add_run(provider_name)
    run.bold = True
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x11, 0x56, 0x7F)

    sub = doc.add_paragraph()
    sub.space_after = Pt(2)
    run = sub.add_run(f"NPI: {provider_npi}")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    date_para = doc.add_paragraph()
    date_para.space_after = Pt(16)
    run = date_para.add_run(datetime.now().strftime("%B %d, %Y"))
    run.font.size = Pt(10)

    doc.add_paragraph("")

    re_block = doc.add_paragraph()
    re_block.space_after = Pt(12)
    lines = [
        f"RE: Appeal of Claim Denial",
        f"Claim Number: {claim_id}",
        f"Member: {member_name}, ID: {member_id}",
        f"Plan: {plan_id}",
        f"Date of Service: {dos}",
        f"Denial Code: {denial_code} — {denial_reason}",
        f"Denial ID: {denial_id}",
    ]
    run = re_block.add_run("RE: Appeal of Claim Denial\n")
    run.bold = True
    run.font.size = Pt(11)
    for line in lines[1:]:
        run = re_block.add_run(f"{line}\n")
        run.font.size = Pt(10)

    doc.add_paragraph("")

    paragraphs = appeal_body.split("\n\n")
    for para_text in paragraphs:
        para_text = para_text.strip()
        if not para_text:
            continue
        p = doc.add_paragraph()
        p.space_after = Pt(8)
        run = p.add_run(para_text)
        run.font.size = Pt(11)

    if policy_citations and policy_citations.strip():
        doc.add_paragraph("")
        cite_heading = doc.add_paragraph()
        cite_heading.space_after = Pt(4)
        run = cite_heading.add_run("Policy Citations Referenced")
        run.bold = True
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x11, 0x56, 0x7F)

        for citation in policy_citations.split(","):
            citation = citation.strip()
            if citation:
                cp = doc.add_paragraph(style="List Bullet")
                run = cp.add_run(citation)
                run.font.size = Pt(10)
                run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)

    doc.add_paragraph("")
    doc.add_paragraph("")

    sig = doc.add_paragraph()
    sig.add_run("Sincerely,\n").font.size = Pt(11)
    sig.add_run("\n")
    run = sig.add_run(provider_name)
    run.bold = True
    run.font.size = Pt(11)
    sig.add_run(f"\nNPI: {provider_npi}").font.size = Pt(10)

    doc.save(output_path)
    return output_path


def upload_to_stage(file_path: str, claim_id: str) -> str:
    import snowflake.connector

    token_path = Path("/snowflake/session/token")
    if token_path.exists():
        conn = snowflake.connector.connect(
            host=os.environ.get("SNOWFLAKE_HOST", ""),
            account=os.environ.get("SNOWFLAKE_ACCOUNT", ""),
            authenticator="oauth",
            token=token_path.read_text().strip(),
            warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
            database=os.environ.get("SNOWFLAKE_DATABASE", "AGENTIC_DENIED_CLAIMS_HANDLING"),
            schema=os.environ.get("SNOWFLAKE_SCHEMA", "DENIED_CLAIMS"),
        )
    else:
        conn = snowflake.connector.connect(
            connection_name=os.getenv("SNOWFLAKE_CONNECTION_NAME", "default")
        )

    try:
        cur = conn.cursor()
        _db = os.environ.get("SNOWFLAKE_DATABASE", "AGENTIC_DENIED_CLAIMS_HANDLING")
        _schema = os.environ.get("SNOWFLAKE_SCHEMA", "DENIED_CLAIMS")
        stage_path = f"@{_db}.{_schema}.APPEAL_DOCUMENTS/{claim_id}/"
        cur.execute(
            f"PUT 'file://{file_path}' '{stage_path}' AUTO_COMPRESS=FALSE OVERWRITE=TRUE"
        )
        result = cur.fetchall()
        print(f"PUT result: {result}", file=sys.stderr)
        filename = os.path.basename(file_path)
        return f"{claim_id}/{filename}"
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Generate appeal DOCX and upload to Snowflake stage")
    parser.add_argument("--claim-id", required=True)
    parser.add_argument("--denial-id", required=True)
    parser.add_argument("--provider-name", required=True)
    parser.add_argument("--provider-npi", required=True)
    parser.add_argument("--member-name", required=True)
    parser.add_argument("--member-id", required=True)
    parser.add_argument("--plan-id", required=True)
    parser.add_argument("--dos", required=True)
    parser.add_argument("--denial-code", required=True)
    parser.add_argument("--denial-reason", required=True)
    parser.add_argument("--appeal-body", required=True)
    parser.add_argument("--policy-citations", default="")
    parser.add_argument("--output-dir", default="/tmp")
    parser.add_argument("--no-upload", action="store_true", help="Skip stage upload")
    args = parser.parse_args()

    filename = f"Appeal_{args.claim_id}.docx"
    output_path = os.path.join(args.output_dir, filename)

    create_appeal_docx(
        claim_id=args.claim_id,
        denial_id=args.denial_id,
        provider_name=args.provider_name,
        provider_npi=args.provider_npi,
        member_name=args.member_name,
        member_id=args.member_id,
        plan_id=args.plan_id,
        dos=args.dos,
        denial_code=args.denial_code,
        denial_reason=args.denial_reason,
        appeal_body=args.appeal_body,
        policy_citations=args.policy_citations,
        output_path=output_path,
    )

    print(f"DOCX generated: {output_path}", file=sys.stderr)

    if args.no_upload:
        print(output_path)
    else:
        stage_path = upload_to_stage(output_path, args.claim_id)
        print(stage_path)


if __name__ == "__main__":
    main()
