import "server-only"
import { fq } from "@/lib/constants"

/**
 * Whitelisted, fixed SQL for every panel in the Command Center.
 * The route handler only accepts keys from this map — no user input is ever
 * interpolated into SQL. Every statement reads a governed VW_* view (or the
 * pre-baked insights model) from the certified data product; nothing is mocked.
 */
export const PANEL_SQL: Record<string, string> = {
  // Band A
  trend: `SELECT MONTH, IS_FORECAST, PMPM_ACTUAL, PMPM_FORECAST_BASE, PMPM_FORECAST_HIGH, PMPM_PLAN, NET_SPEND, TREND_ANNUAL_PCT FROM ${fq("VW_PMPM_TREND")} ORDER BY MONTH`,
  pvm: `SELECT COMPONENT, AMOUNT, PCT_OF_TREND, TOTAL_CHANGE FROM ${fq("VW_TREND_PVM")}`,
  // Band B
  benefit: `SELECT BENEFIT_TYPE, NET_SPEND, GROSS_SPEND, CLAIM_LINES, PCT_OF_NET_SPEND FROM ${fq("VW_SPEND_BY_BENEFIT")}`,
  hicost: `SELECT THERAPEUTIC_CLASS, NET_SPEND_CURRENT, NET_SPEND_PRIOR, YOY_GROWTH_PCT FROM ${fq("VW_HIGH_COST_CLASSES")}`,
  contrib: `SELECT THERAPEUTIC_CLASS, DOLLARS_ADDED_YOY, YOY_GROWTH_PCT, VOLUME_EFFECT, PRICE_EFFECT, MIX_EFFECT, DOMINANT_DRIVER, DRIVER_RANK FROM ${fq("VW_TREND_CONTRIBUTORS")}`,
  // Band C
  bridge: `SELECT LEVER_ORDER, LEVER_KEY, LEVER_NAME, STATUS, GROSS_POOL, CAPTURE_RATE, ADDRESSABLE_AMOUNT, PCT_OF_TOTAL, RATIONALE FROM ${fq("VW_ADDRESSABLE_BRIDGE")} ORDER BY LEVER_ORDER`,
  waste: `SELECT CLAIMANT_BAND, MEMBERS, NET_SPEND, PCT_OF_SPEND FROM ${fq("VW_WASTE_CONCENTRATION")}`,
  // Band D
  rebate: `SELECT THERAPEUTIC_CLASS, REBATE_AMOUNT, GROSS_SPEND, REBATE_YIELD_PCT FROM ${fq("VW_REBATE_YIELD")} ORDER BY REBATE_YIELD_PCT ASC`,
  offform: `SELECT DRUG_NAME, THERAPEUTIC_CLASS, STEERABLE_NET_SPEND, CLAIM_LINES FROM ${fq("VW_FORMULARY_LEAKAGE")}`,
  pa: `SELECT DECISION, PA_COUNT, PCT_OF_TOTAL FROM ${fq("VW_PA_OUTCOMES")}`,
  adherence: `SELECT THERAPEUTIC_CLASS, AVG_PDC, ADHERENT_PCT, MEASURED_MEMBERS, PDC_THRESHOLD FROM ${fq("VW_ADHERENCE_BY_CLASS")}`,
}

export const KPI_SQL = `SELECT NET_PMPM_CURRENT, NET_PMPM_PRIOR, PMPM_YOY_PCT, TARGET_PMPM, PMPM_VS_PLAN, PROJECTED_NEXT12_SPEND, ADDRESSABLE_TOTAL, NET_SPEND_CURRENT_12, ADDRESSABLE_PCT_OF_SPEND FROM ${fq("VW_KPI_SUMMARY")}`

export const INSIGHTS_SQL = `SELECT TAB_ORDER, TAB_KEY, TAB_TITLE, AGENT_PERSONA, INSIGHT_MD, TAGS, GENERATED_AT FROM ${fq("MDL_TAB_INSIGHTS")} ORDER BY TAB_ORDER`

export function isPanelKey(key: string): key is keyof typeof PANEL_SQL {
  return Object.prototype.hasOwnProperty.call(PANEL_SQL, key)
}
